function path=add_wind_source_dc(parent,name,cfg,pos)
%ADD_WIND_SOURCE_DC System-level wind availability, dispatch and DC buffer.
path=[parent '/' name];add_block('built-in/Subsystem',path,'Position',pos, ...
    'BackgroundColor','[0.84,0.94,0.82]','ContentPreviewEnabled','off', ...
    'AttributesFormatString','replaceable by turbine + PMSG + MSC + physical DC link');
add_block('simulink/Ports & Subsystems/In1',[path '/ResourceCommandBus'], ...
    'Position',[20 125 50 139],'OutDataTypeStr','Bus: ResourceCommandBus');
add_block('simulink/Signal Routing/Bus Selector',[path '/Command Selector'], ...
    'Position',[80 55 85 250], ...
    'OutputSignals','P_ref_W,Q_ref_var,V_ref_V,f_ref_Hz,enable,mode');
add_block('simulink/Sources/Constant',[path '/Available Base'], ...
    'Position',[125 20 230 50],'Value',[cfg '.source.P_available_base_W']);
add_block('simulink/Sources/Step',[path '/Available Increment'], ...
    'Position',[125 65 230 95],'Time',[cfg '.source.P_available_step_time_s'], ...
    'Before','0','After',[cfg '.source.P_available_step_W']);
add_block('simulink/Math Operations/Sum',[path '/Available Command'], ...
    'Position',[265 30 295 90],'Inputs','++');
add_block('simulink/Discontinuities/Saturation',[path '/Available Power Limit'], ...
    'Position',[335 40 455 80],'LowerLimit','0','UpperLimit',[cfg '.source.P_available_W']);
add_block('simulink/Continuous/Transfer Fcn',[path '/Mechanical Power Response'], ...
    'Position',[500 40 620 80],'Numerator','1', ...
    'Denominator',['[' cfg '.source.mechanical_tau_s 1]']);
add_block('simulink/Discontinuities/Saturation',[path '/Dispatch Limit'], ...
    'Position',[145 285 260 325],'LowerLimit','0','UpperLimit',[cfg '.rating.P_W']);
add_block('simulink/Math Operations/MinMax',[path '/Available versus Dispatch'], ...
    'Position',[675 55 735 110],'Function','min','Inputs','2');
add_block('simulink/Discontinuities/Rate Limiter',[path '/MSC Power Ramp'], ...
    'Position',[775 55 885 95],'RisingSlewLimit',[cfg '.source.ramp_up_Wps'], ...
    'FallingSlewLimit',[cfg '.source.ramp_down_Wps'],'InitialCondition','0');
add_block('simulink/Continuous/Transfer Fcn',[path '/DC Energy Buffer'], ...
    'Position',[925 55 1040 95],'Numerator','1','Denominator',['[' cfg '.source.dc_tau_s 1]']);
add_block('simulink/Signal Routing/Bus Creator',[path '/PCS Command'], ...
    'Position',[1100 45 1105 255],'Inputs','6','OutDataTypeStr','Bus: ResourceCommandBus');
add_block('simulink/Ports & Subsystems/Out1',[path '/PCSCommandBus'], ...
    'Position',[1160 135 1190 149],'Port','1','OutDataTypeStr','Bus: ResourceCommandBus');

add_block('simulink/Math Operations/Sum',[path '/DC Power Imbalance'], ...
    'Position',[790 370 820 430],'Inputs','+-');
add_block('simulink/Continuous/Integrator',[path '/DC Energy Delta'], ...
    'Position',[855 380 895 420],'InitialCondition','0');
add_block('simulink/Math Operations/Bias',[path '/Nominal DC Energy'], ...
    'Position',[930 380 1045 420], ...
    'Bias',['0.5*' cfg '.source.dc_equiv_F*' cfg '.source.dc_nominal_V^2']);
add_block('simulink/User-Defined Functions/Fcn',[path '/Vdc from Energy'], ...
    'Position',[1080 380 1205 420], ...
    'Expr',['sqrt(abs(2*u/' cfg '.source.dc_equiv_F))']);
add_block('simulink/Math Operations/Gain',[path '/Energy state pu'], ...
    'Position',[1080 440 1205 475], ...
    'Gain',['1/(0.5*' cfg '.source.dc_equiv_F*' cfg '.source.dc_nominal_V^2)']);
add_block('simulink/Math Operations/Gain',[path '/MPPT capture pu'], ...
    'Position',[675 455 790 490],'Gain',['1/' cfg '.rating.P_W']);
add_block('simulink/Signal Routing/Bus Creator',[path '/Source Status'], ...
    'Position',[1260 300 1265 510],'Inputs','5','OutDataTypeStr','Bus: SourceStatusBus');
add_block('simulink/Ports & Subsystems/Out1',[path '/SourceStatusBus'], ...
    'Position',[1320 395 1350 409],'Port','2','OutDataTypeStr','Bus: SourceStatusBus');

add_line(path,'ResourceCommandBus/1','Command Selector/1');
add_line(path,'Available Base/1','Available Command/1');
add_line(path,'Available Increment/1','Available Command/2');
add_line(path,'Available Command/1','Available Power Limit/1');
add_line(path,'Available Power Limit/1','Mechanical Power Response/1');
add_line(path,'Command Selector/1','Dispatch Limit/1');
add_line(path,'Mechanical Power Response/1','Available versus Dispatch/1');
add_line(path,'Dispatch Limit/1','Available versus Dispatch/2');
add_line(path,'Available versus Dispatch/1','MSC Power Ramp/1');
add_line(path,'MSC Power Ramp/1','DC Energy Buffer/1');
cmdFields={'P_ref_W','Q_ref_var','V_ref_V','f_ref_Hz','enable','mode'};
v2_named_line(path,'DC Energy Buffer/1','PCS Command/1',cmdFields{1});
for k=2:6,add_line(path,sprintf('Command Selector/%d',k),sprintf('PCS Command/%d',k),'autorouting','on');end
add_line(path,'PCS Command/1','PCSCommandBus/1');
% DC energy changes only by the mismatch between actual MSC output and PCS
% DC input.  The upstream availability/dispatch request is not yet physical
% power and therefore must not be integrated into the DC capacitor.
add_line(path,'MSC Power Ramp/1','DC Power Imbalance/1');
add_line(path,'DC Energy Buffer/1','DC Power Imbalance/2');
add_line(path,'DC Power Imbalance/1','DC Energy Delta/1');
add_line(path,'DC Energy Delta/1','Nominal DC Energy/1');
add_line(path,'Nominal DC Energy/1','Vdc from Energy/1');
add_line(path,'Nominal DC Energy/1','Energy state pu/1');
add_line(path,'Mechanical Power Response/1','MPPT capture pu/1');
st={'Mechanical Power Response/1','Dispatch Limit/1','Energy state pu/1','Vdc from Energy/1','MPPT capture pu/1'};
fields={'available_power_W','dispatch_limit_W','energy_state_pu','Vdc_V','mppt_capture_pu'};
for k=1:5,v2_named_line(path,st{k},sprintf('Source Status/%d',k),fields{k});end
add_line(path,'Source Status/1','SourceStatusBus/1');v2_route_level(path);
end
