function path=add_local_pll(parent,name,cfg,pos)
%ADD_LOCAL_PLL Build the shared PCC-local phase PLL used by every GFL PCS.
path=[parent '/' name];
add_block('built-in/Subsystem',path,'Position',pos,'BackgroundColor','[0.84,0.92,1.00]', ...
    'ContentPreviewEnabled','off','AttributesFormatString','local PCC voltage only');
add_block('simulink/Ports & Subsystems/In1',[path '/Vabc'],'Position',[20 78 50 92]);
add_block('simulink/User-Defined Functions/Fcn',[path '/Measured Phase'], ...
    'Position',[85 65 285 105], ...
    'Expr','atan2((2/3)*(u(1)-0.5*u(2)-0.5*u(3)),(sqrt(3)/3)*(u(3)-u(2)))');
add_block('simulink/Signal Routing/Mux',[path '/Phase Pair'], ...
    'Position',[320 55 325 145],'Inputs','2');
add_block('simulink/User-Defined Functions/Fcn',[path '/Wrapped Phase Error'], ...
    'Position',[360 75 520 115],'Expr','atan2(sin(u(1)-u(2)),cos(u(1)-u(2)))');
add_block('simulink/Math Operations/Gain',[path '/PLL Kp'], ...
    'Position',[555 40 635 70],'Gain',[cfg '.control.pll_Kp']);
add_block('simulink/Math Operations/Gain',[path '/PLL Ki'], ...
    'Position',[555 120 635 150],'Gain',[cfg '.control.pll_Ki']);
add_block('simulink/Continuous/Integrator',[path '/Error Integral'], ...
    'Position',[670 115 710 155],'InitialCondition','0');
add_block('simulink/Math Operations/Sum',[path '/Delta Omega'], ...
    'Position',[750 60 780 130],'Inputs','++');
add_block('simulink/Sources/Constant',[path '/Nominal Omega'], ...
    'Position',[745 15 840 45],'Value',['2*pi*' cfg '.rating.f_Hz']);
add_block('simulink/Math Operations/Sum',[path '/Omega Command'], ...
    'Position',[870 55 900 115],'Inputs','++');
add_block('simulink/Discontinuities/Saturation',[path '/Omega Limits'], ...
    'Position',[935 65 1020 105], ...
    'UpperLimit',['2*pi*' cfg '.control.pll_max_Hz'], ...
    'LowerLimit',['2*pi*' cfg '.control.pll_min_Hz']);
add_block('simulink/Continuous/Integrator',[path '/Angle Integrator'], ...
    'Position',[1060 65 1100 105],'InitialCondition',[cfg '.control.pll_theta0_rad']);
add_block('simulink/Ports & Subsystems/Out1',[path '/theta'], ...
    'Position',[1150 55 1180 69],'Port','1');
add_block('simulink/Ports & Subsystems/Out1',[path '/omega'], ...
    'Position',[1150 105 1180 119],'Port','2');
add_block('simulink/Ports & Subsystems/Out1',[path '/phase_error'], ...
    'Position',[1150 155 1180 169],'Port','3');
add_line(path,'Vabc/1','Measured Phase/1');add_line(path,'Measured Phase/1','Phase Pair/1');
add_line(path,'Angle Integrator/1','Phase Pair/2');add_line(path,'Phase Pair/1','Wrapped Phase Error/1');
add_line(path,'Wrapped Phase Error/1','PLL Kp/1');add_line(path,'Wrapped Phase Error/1','PLL Ki/1');
add_line(path,'PLL Ki/1','Error Integral/1');add_line(path,'PLL Kp/1','Delta Omega/1');
add_line(path,'Error Integral/1','Delta Omega/2');add_line(path,'Delta Omega/1','Omega Command/1');
add_line(path,'Nominal Omega/1','Omega Command/2');add_line(path,'Omega Command/1','Omega Limits/1');
add_line(path,'Omega Limits/1','Angle Integrator/1');add_line(path,'Angle Integrator/1','theta/1');
add_line(path,'Omega Limits/1','omega/1');add_line(path,'Wrapped Phase Error/1','phase_error/1');
end
