function path=add_pv_source_dc(parent,name,cfg,pos)
%ADD_PV_SOURCE_DC System-level PV availability and replaceable DC boundary.
path=[parent '/' name];add_block('built-in/Subsystem',path,'Position',pos, ...
    'BackgroundColor','[0.84,0.94,0.82]','ContentPreviewEnabled','off', ...
    'AttributesFormatString','system-level PV availability / replaceable by array+MPPT+DC-DC');
add_block('simulink/Ports & Subsystems/In1',[path '/ResourceCommandBus'], ...
    'Position',[20 95 50 109],'OutDataTypeStr','Bus: ResourceCommandBus');
add_block('simulink/Signal Routing/Bus Selector',[path '/Command Selector'], ...
    'Position',[80 40 85 205], ...
    'OutputSignals','P_ref_W,Q_ref_var,V_ref_V,f_ref_Hz,enable,mode');
add_block('simulink/Discontinuities/Saturation',[path '/Available Power Limit'], ...
    'Position',[145 35 270 70],'LowerLimit','0','UpperLimit',[cfg '.source.P_available_W']);
add_block('simulink/Discontinuities/Rate Limiter',[path '/PV Power Ramp'], ...
    'Position',[295 35 405 75], ...
    'RisingSlewLimit',[cfg '.source.ramp_up_Wps'], ...
    'FallingSlewLimit',[cfg '.source.ramp_down_Wps'], ...
    'InitialCondition','0');
add_block('simulink/Continuous/Transfer Fcn',[path '/DC-side Power Response'], ...
    'Position',[440 35 555 75],'Numerator','1','Denominator',['[' cfg '.source.dc_tau_s 1]']);
add_block('simulink/Signal Routing/Bus Creator',[path '/PCS Command'], ...
    'Position',[610 35 615 230],'Inputs','6','OutDataTypeStr','Bus: ResourceCommandBus');
add_block('simulink/Ports & Subsystems/Out1',[path '/PCSCommandBus'], ...
    'Position',[670 105 700 119],'Port','1','OutDataTypeStr','Bus: ResourceCommandBus');
add_block('simulink/Sources/Constant',[path '/P available'], ...
    'Position',[145 270 260 300],'Value',[cfg '.source.P_available_W']);
add_block('simulink/Sources/Constant',[path '/Dispatch limit'], ...
    'Position',[145 315 260 345],'Value',[cfg '.rating.P_W']);
add_block('simulink/Sources/Constant',[path '/Energy state'], ...
    'Position',[145 360 260 390],'Value','1');
add_block('simulink/Sources/Constant',[path '/Vdc proxy'], ...
    'Position',[145 405 260 435],'Value',[cfg '.source.dc_nominal_V']);
add_block('simulink/Sources/Constant',[path '/MPPT capture'], ...
    'Position',[145 450 260 480],'Value','1');
add_block('simulink/Signal Routing/Bus Creator',[path '/Source Status'], ...
    'Position',[490 275 495 480],'Inputs','5','OutDataTypeStr','Bus: SourceStatusBus');
add_block('simulink/Ports & Subsystems/Out1',[path '/SourceStatusBus'], ...
    'Position',[550 370 580 384],'Port','2','OutDataTypeStr','Bus: SourceStatusBus');
add_line(path,'ResourceCommandBus/1','Command Selector/1');
add_line(path,'Command Selector/1','Available Power Limit/1');
add_line(path,'Available Power Limit/1','PV Power Ramp/1');
add_line(path,'PV Power Ramp/1','DC-side Power Response/1');
cmdFields={'P_ref_W','Q_ref_var','V_ref_V','f_ref_Hz','enable','mode'};
v2_named_line(path,'DC-side Power Response/1','PCS Command/1',cmdFields{1});
for k=2:6,add_line(path,sprintf('Command Selector/%d',k),sprintf('PCS Command/%d',k),'autorouting','on');end
add_line(path,'PCS Command/1','PCSCommandBus/1');
st={'P available/1','Dispatch limit/1','Energy state/1','Vdc proxy/1','MPPT capture/1'};
stFields={'available_power_W','dispatch_limit_W','energy_state_pu','Vdc_V','mppt_capture_pu'};
for k=1:5,v2_named_line(path,st{k},sprintf('Source Status/%d',k),stFields{k});end
add_line(path,'Source Status/1','SourceStatusBus/1');v2_route_level(path);
end
