function path=add_average_current_converter(parent,name,cfg,pos)
%ADD_AVERAGE_CURRENT_CONVERTER Controlled-current average PCS plant.
path=[parent '/' name];add_block('built-in/Subsystem',path,'Position',pos, ...
    'BackgroundColor','[0.84,0.92,1.00]','ContentPreviewEnabled','off');
add_block('simulink/Ports & Subsystems/In1',[path '/iabc_A'], ...
    'Position',[20 80 50 94]);
v2_add_pmio(path,'AC_690V',1,'Right','foundation.electrical.three_phase',[535 80 565 110]);
sps=sprintf('nesl_utility/Simulink-PS\nConverter');
pss=sprintf('nesl_utility/PS-Simulink\nConverter');
ccs=sprintf('ee_lib/Sources/Controlled Current\nSource\n(Three-Phase)');
iv=sprintf('ee_lib/Sensors &\nTransducers/Current and Voltage\nSensor (Three-Phase)');
add_block(sps,[path '/Current Command to PS'],'Position',[85 55 185 115], ...
    'Unit','A','FilteringAndDerivatives','zero');
add_block(ccs,[path '/Average Current Injection'],'Position',[225 45 335 125], ...
    'input_option','ee.enum.inputType.instantaneous','FRated',[cfg '.rating.f_Hz']);
add_block(iv,[path '/Converter-Side VI Sensor'],'Position',[365 45 445 125], ...
    'vMeasurementType','ee.enum.vmeasurement.ll');
add_block(pss,[path '/iabc to Simulink'],'Position',[360 175 465 210],'Unit','A');
add_block(pss,[path '/vabc to Simulink'],'Position',[360 225 465 260],'Unit','V');
add_block('simulink/Ports & Subsystems/Out1',[path '/iabc_actual_A'], ...
    'Position',[520 180 550 194],'Port','1');
add_block('simulink/Ports & Subsystems/Out1',[path '/vabc_converter_V'], ...
    'Position',[520 230 550 244],'Port','2');
add_block('fl_lib/Electrical/Electrical Elements/Electrical Reference', ...
    [path '/Converter Neutral'],'Position',[235 160 265 190]);
add_line(path,'iabc_A/1','Current Command to PS/1');
add_line(path,v2_port([path '/Current Command to PS'],'RConn',1), ...
    v2_port([path '/Average Current Injection'],'LConn',1));
add_line(path,v2_port([path '/Average Current Injection'],'LConn',2), ...
    v2_port([path '/Converter Neutral'],'LConn',1));
add_line(path,v2_port([path '/Average Current Injection'],'RConn',1), ...
    v2_port([path '/Converter-Side VI Sensor'],'LConn',1));
add_line(path,v2_port([path '/Converter-Side VI Sensor'],'RConn',3), ...
    v2_physical_port([path '/AC_690V']));
add_line(path,v2_port([path '/Converter-Side VI Sensor'],'RConn',2), ...
    v2_port([path '/iabc to Simulink'],'LConn',1));
add_line(path,v2_port([path '/Converter-Side VI Sensor'],'RConn',1), ...
    v2_port([path '/vabc to Simulink'],'LConn',1));
add_line(path,'iabc to Simulink/1','iabc_actual_A/1');
add_line(path,'vabc to Simulink/1','vabc_converter_V/1');
end
