function path=add_current_circle_limiter(parent,name,cfg,pos)
%ADD_CURRENT_CIRCLE_LIMITER Apply enable gating and a circular dq limit.
path=[parent '/' name];add_block('built-in/Subsystem',path,'Position',pos, ...
    'BackgroundColor','[1.00,0.91,0.76]','ContentPreviewEnabled','off');
ins={'Id_raw_Apk','Iq_raw_Apk','enable'};
for k=1:3,add_block('simulink/Ports & Subsystems/In1',[path '/' ins{k}], ...
        'Port',num2str(k),'Position',[20 35+55*(k-1) 50 49+55*(k-1)]);end
add_block('simulink/Signal Routing/Mux',[path '/raw dq'], ...
    'Position',[90 35 95 125],'Inputs','2');
add_block('simulink/Math Operations/Product',[path '/Enable Gate'], ...
    'Position',[135 45 175 120],'Inputs','2');
add_block('simulink/User-Defined Functions/Fcn',[path '/Magnitude'], ...
    'Position',[220 20 330 50],'Expr','sqrt(u(1)^2+u(2)^2)');
add_block('simulink/User-Defined Functions/Fcn',[path '/Raw Factor'], ...
    'Position',[365 20 490 50],'Expr',[cfg '.control.Ilimit_peak_A/(u+1e-9)']);
add_block('simulink/Discontinuities/Saturation',[path '/Circle Factor'], ...
    'Position',[525 15 610 55],'LowerLimit','0','UpperLimit','1');
add_block('simulink/Math Operations/Product',[path '/Apply Factor'], ...
    'Position',[650 50 690 125],'Inputs','2');
add_block('simulink/Signal Routing/Demux',[path '/limited dq'], ...
    'Position',[735 45 740 130],'Outputs','2');
add_block('simulink/User-Defined Functions/Fcn',[path '/Limit Active'], ...
    'Position',[650 160 770 190],'Expr','u<0.999999');
outs={'Id_ref_Apk','Iq_ref_Apk','limit_factor','limit_active'};
ys=[55 105 155 205];for k=1:4,add_block('simulink/Ports & Subsystems/Out1',[path '/' outs{k}], ...
        'Port',num2str(k),'Position',[830 ys(k) 860 ys(k)+14]);end
add_line(path,'Id_raw_Apk/1','raw dq/1');add_line(path,'Iq_raw_Apk/1','raw dq/2');
add_line(path,'raw dq/1','Enable Gate/1');add_line(path,'enable/1','Enable Gate/2');
add_line(path,'Enable Gate/1','Magnitude/1');add_line(path,'Magnitude/1','Raw Factor/1');
add_line(path,'Raw Factor/1','Circle Factor/1');add_line(path,'Enable Gate/1','Apply Factor/1');
add_line(path,'Circle Factor/1','Apply Factor/2');add_line(path,'Apply Factor/1','limited dq/1');
add_line(path,'limited dq/1','Id_ref_Apk/1');add_line(path,'limited dq/2','Iq_ref_Apk/1');
add_line(path,'Circle Factor/1','limit_factor/1');add_line(path,'Circle Factor/1','Limit Active/1');
add_line(path,'Limit Active/1','limit_active/1');
end
