function path=add_resource_status_assembly(parent,name,pos)
%ADD_RESOURCE_STATUS_ASSEMBLY Map local typed buses to the common status API.
path=[parent '/' name];add_block('built-in/Subsystem',path,'Position',pos, ...
    'BackgroundColor','[0.92,0.92,0.92]','ContentPreviewEnabled','off', ...
    'AttributesFormatString','typed local buses -> ResourceStatusBus');
types={'SourceStatusBus','PCSStatusBus','PCCMeasurementBus'};names={'Source','PCS','PCC'};
for k=1:3,add_block('simulink/Ports & Subsystems/In1',[path '/' names{k}], ...
        'Port',num2str(k),'Position',[20 55+100*(k-1) 50 69+100*(k-1)], ...
        'OutDataTypeStr',['Bus: ' types{k}]);end
add_block('simulink/Signal Routing/Bus Selector',[path '/Source Selector'], ...
    'Position',[90 30 95 125],'OutputSignals','available_power_W,energy_state_pu,Vdc_V');
add_block('simulink/Signal Routing/Bus Selector',[path '/PCS Selector'], ...
    'Position',[90 130 95 235], ...
    'OutputSignals','frequency_Hz,current_limit_factor,control_mode,healthy');
add_block('simulink/Signal Routing/Bus Selector',[path '/PCC Selector'], ...
    'Position',[90 245 95 355],'OutputSignals','P_W,Q_var,Vll_rms_V');
add_block('simulink/Math Operations/Sum',[path '/Power Headroom'], ...
    'Position',[260 45 290 95],'Inputs','+-');
add_block('simulink/Math Operations/Gain',[path '/Vpcc Pass'], ...
    'Position',[250 270 320 300],'Gain','1');
add_line(path,'PCC Selector/3','Vpcc Pass/1','autorouting','on');
add_block('simulink/Signal Routing/Bus Creator',[path '/Resource Status'], ...
    'Position',[420 35 425 365],'Inputs','11','OutDataTypeStr','Bus: ResourceStatusBus');
add_block('simulink/Ports & Subsystems/Out1',[path '/ResourceStatusBus'], ...
    'Position',[500 190 530 204],'OutDataTypeStr','Bus: ResourceStatusBus');
add_line(path,'Source/1','Source Selector/1');add_line(path,'PCS/1','PCS Selector/1');add_line(path,'PCC/1','PCC Selector/1');
add_line(path,'Source Selector/1','Power Headroom/1');add_line(path,'PCC Selector/1','Power Headroom/2');
sig={'PCC Selector/1','PCC Selector/2','Vpcc Pass/1','PCS Selector/1','Source Selector/1', ...
    'Power Headroom/1','PCS Selector/2','Source Selector/2','Source Selector/3','PCS Selector/3','PCS Selector/4'};
fields={'P_W','Q_var','Vpcc_V','frequency_Hz','available_power_W','power_headroom_W', ...
    'current_limit_factor','energy_state_pu','Vdc_V','control_mode','healthy'};
for k=1:numel(sig)
    if any(k==[3 6]),v2_named_line(path,sig{k},sprintf('Resource Status/%d',k),fields{k});
    else,add_line(path,sig{k},sprintf('Resource Status/%d',k),'autorouting','on');end
end
add_line(path,'Resource Status/1','ResourceStatusBus/1');v2_route_level(path);
end
