function results=run_gfm_c0_checks
root=fileparts(mfilename('fullpath'));addpath(root);init_project;
run(fullfile(root,'Parameters','gfm_parameters.m'));assignin('base','GFM',GFM);
model='GFM_Inverter_C0';load_system(fullfile(root,[model '.slx']));
cleanup=onCleanup(@()bdclose(model)); %#ok<NASGU>
bridge=[model '/Two-Level VSC/Two-Level Three-Phase Bridge'];
assert(strcmp(get_param(bridge,'Vth'),'Converter.GateThreshold_V'), ...
    'GFM branch bridge threshold is not branch-parameterized.');
assert(strcmp(get_param(bridge,'diode_param'), ...
    'ee.enum.converters.protectiondiode.nodynamics'), ...
    'GFM branch bridge protection diode is not enabled.');
for k=1:6
    gate=sprintf('%s/Two-Level VSC/Gate %d to Physical Signal',model,k);
    assert(strcmp(get_param(gate,'Unit'),'V'),'Gate %d converter must output volts.',k);
end
zcBlocks={ ...
    [model '/GFM Controller/01 Measurements and Power/Abs Current'], ...
    [model '/GFM Controller/01 Measurements and Power/Peak Phase Current'], ...
    [model '/GFM Controller/04 Voltage Reference and Limits/Safe Ipeak']};
for k=1:numel(zcBlocks)
    assert(strcmp(get_param(zcBlocks{k},'ZeroCross'),'off'), ...
        'Measurement/current-limit block must not generate continuous zero-crossing events: %s',zcBlocks{k});
end
gridSource=[model '/Grid Equivalent and Source/Ideal Three-Phase Grid Source'];
assert(strcmp(get_param(gridSource,'impedance_option'),'0'), ...
    'Grid source internal impedance must be disabled; explicit Rg+Lg already owns the Thevenin impedance.');
xfmr=[model '/Grid Interface (Filter XFMR PCC)/0.69 kV to 10 kV Step-Up Transformer'];
assert(strcmp(get_param(xfmr,'leakage_reactance_option'), ...
    'ee.enum.transformer_leakage.include'), ...
    'Transformer leakage reactance parameters are present but not enabled.');
required={'GFM Controller','GFM Controller/01 Measurements and Power', ...
    'GFM Controller/02 P-f Droop and Angle', ...
    'GFM Controller/03 Q-V Droop and Magnitude', ...
    'GFM Controller/04 Voltage Reference and Limits', ...
    'GFM Controller/05 Carrier PWM'};
for k=1:numel(required),assert(getSimulinkBlockHandle([model '/' required{k}],true)>0,'Missing %s',required{k});end
assert(isempty(find_system(model,'LookUnderMasks','all','FollowLinks','on', ...
    'BlockType','SubSystem','SFBlockType','MATLAB Function')),'Controller must remain graphical.');
set_param(model,'SimulationCommand','update');
results=struct('Model',model,'DiagramUpdate','passed','StructuralChecks','passed', ...
    'ControllerSubsystems',numel(required),'MATLABFunctionBlocks',0);
disp(results)
end
