function T=define_strong_machine_fixture(assignToBase)
%DEFINE_STRONG_MACHINE_FIXTURE Parameters for the GFL commissioning grid.
% This fixture is not a renewable resource and is excluded from Stage 2.
if nargin<1,assignToBase=true;end
T=struct();
T.Grid=struct('frequency',50,'voltage',10e3);
T.GridTransformer=struct('hv',10e3,'lv',10e3,'VA',25e6, ...
    'winding_resistance',0.01,'winding_lekage_reactance',0.08, ...
    'zero_sequence_reactance',0.10);
T.SM=struct('MVA',25e6,'Voltage',10e3,'polepairs',1,'w_sm',2*pi*50, ...
    'field_current',1300,'Base_Torque_SM',25e6/(2*pi*50), ...
    'initial_torque',0.20,'initial_Pe',5e6,'initial_Qe',0, ...
    'stator_resistance',0.003,'lekage_reactance',0.15, ...
    'xd',1.81,'xq',1.76,'xd_',0.30,'xq_',0.65, ...
    'xd_dash',0.23,'xq_dash',0.25,'Tdo_',8,'Tdo_dash',0.03, ...
    'Tqo_',1,'Tqo_dash',0.07,'inertia',5.0,'damping',0.02, ...
    'speed_reference',1.0,'droop_p',1,'load_reference_set_point',0.20, ...
    'governor_time_constant',0.02,'time_constsnt_steamchest',0.03, ...
    'P_load',5e6,'Q_load',1.0e6);
T.SimulationTime=1.0;T.Ts=5e-5;
if assignToBase
    assignin('base','Grid',T.Grid);assignin('base','GridTransformer',T.GridTransformer);
    assignin('base','SM',T.SM);assignin('base','SimulationTime',T.SimulationTime);
    assignin('base','Ts',T.Ts);
end
end
