function C=define_v2_parameters(assignToBase)
%DEFINE_V2_PARAMETERS Independent resource configs on one project base.
if nargin<1,assignToBase=true;end
C=struct();C.base=struct('S_VA',10e6,'V_pcc_V',10e3,'f_Hz',50);

commonRating=struct('P_W',5e6,'S_VA',6.25e6,'V_ac_low_V',690, ...
    'V_pcc_V',10e3,'f_Hz',50,'current_limit_pu',1.10);
w0=2*pi*commonRating.f_Hz;zbase=commonRating.V_ac_low_V^2/commonRating.S_VA;
commonFilter=struct('R1_ohm',0.005*zbase,'L1_H',0.08*zbase/w0, ...
    'R2_ohm',0.005*zbase,'L2_H',0.03*zbase/w0, ...
    'C_F',0.05*commonRating.S_VA/(w0*commonRating.V_ac_low_V^2));
fres=(1/(2*pi))*sqrt((commonFilter.L1_H+commonFilter.L2_H)/ ...
    (commonFilter.L1_H*commonFilter.L2_H*commonFilter.C_F));
commonFilter.Rd_ohm=1/(3*2*pi*fres*commonFilter.C_F);
commonTransformer=struct('S_VA',6.3e6,'V1_V',690,'V2_V',10e3, ...
    'R_pu',0.010,'X_pu',0.060);
commonFeeder=struct('enabled',false,'length_km',0,'R_ohm_per_km',0.026, ...
    'L_H_per_km',2.1e-4);

C.PV=resource_shell('PV','GFL',commonRating,commonFilter,commonTransformer,commonFeeder);
C.PV.source=struct('P_available_W',5e6,'dc_nominal_V',1500,'dc_tau_s',0.002, ...
    'ramp_up_Wps',20e6,'ramp_down_Wps',-20e6);
C.PV.control=struct('current_bandwidth_Hz',150,'pll_min_Hz',45, ...
    'pll_max_Hz',55,'pll_Kp',200,'pll_Ki',5000,'pll_theta0_rad',pi/6, ...
    'Ibase_rms_A',commonRating.S_VA/(sqrt(3)*commonRating.V_ac_low_V), ...
    'Ilimit_peak_A',sqrt(2)*1.10*commonRating.S_VA/(sqrt(3)*commonRating.V_ac_low_V), ...
    'enable_semantics','converter_enable');

C.Wind=resource_shell('Wind','GFL',commonRating,commonFilter,commonTransformer,commonFeeder);
C.Wind.source=struct('P_available_W',5e6,'mechanical_tau_s',0.050, ...
    'ramp_up_Wps',20e6,'ramp_down_Wps',-20e6,'dc_nominal_V',1500, ...
    'dc_equiv_F',0.200,'dc_tau_s',0.002);
C.Wind.control=C.PV.control;

C.BESS=resource_shell('BESS','GFM',commonRating,commonFilter,commonTransformer,commonFeeder);
C.BESS.source=struct('P_W',5e6,'E_Wh',10e6,'battery_nominal_V',1200, ...
    'capacity_Ah',10e6/1200,'dc_ref_V',1500,'SOC_initial',0.55, ...
    'SOC_min',0.20,'SOC_max',0.90,'Ibat_limit_A',4500);
C.BESS.control=struct('P_f_Hz_per_MW',0.20,'Q_V_V_per_Mvar',13.8, ...
    'Rvirt_pu',0.02,'Xvirt_pu',0.10,'ac_current_limit_pu',1.20);

C.assembly=struct('load_P_W',5e6,'load_Q_var',1.5e6, ...
    'event_time_s',0.30,'coordinator_sample_s',0.005);
C.test_grid=struct('Vll_V',10e3,'f_Hz',50,'R_ohm',0.01,'L_H',0.3e-3, ...
    'load_P_W',5e6,'load_Q_var',1.5e6);
if assignToBase,assignin('base','V2',C);end
end

function r=resource_shell(name,mode,rating,filter,transformer,feeder)
r=struct('name',name,'mode',mode,'rating',rating,'filter',filter, ...
    'transformer',transformer,'feeder',feeder);
end
