% Build a standalone physical BESS-GFM source-equivalent validation model.
% PV and wind models are intentionally untouched in this stage.
scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(scriptDir);
run(fullfile(scriptDir, 'init_bess_gfm_stage.m'));

modelName = 'BESS_GFM_10kV_Physical_R4';
modelFile = fullfile(projectRoot,'build',[modelName '.slx']);
pngFile = fullfile(projectRoot,'build',[modelName '.png']);
if bdIsLoaded(modelName), close_system(modelName,0); end
new_system(modelName); open_system(modelName);
load_system('ee_lib'); load_system('simscape'); load_system('nesl_utility');

cvs3 = sprintf('ee_lib/Sources/Controlled Voltage\nSource\n(Three-Phase)');
pq3 = sprintf('ee_lib/Sensors &\nTransducers/Power Sensor\n(Three-Phase)');
eref = 'fl_lib/Electrical/Electrical Elements/Electrical Reference';
gnd3 = sprintf('ee_lib/Connectors &\nReferences/Grounded Neutral\n(Three-Phase)');
rlc3 = 'ee_lib/Passive/RLC Assemblies/RLC (Three-Phase)';
xfmr3 = sprintf('ee_lib/Passive/Transformers/Two-Winding\nTransformer\n(Three-Phase)');
cpl3 = 'ee_lib/Passive/Constant Power Load (Three-Phase)';
sps = sprintf('nesl_utility/Simulink-PS\nConverter');
pss = sprintf('nesl_utility/PS-Simulink\nConverter');

% Physical BESS-GFM source equivalent and AC plant.
add_block(cvs3,[modelName '/BESS_GFM_Controlled_Source'], ...
    'Position',[100 135 210 225], ...
    'input_option','ee.enum.inputType.singleFreqAC','FRated','G.f0_Hz');
add_block(eref,[modelName '/Source_Neutral'], 'Position',[55 190 80 215]);
add_block(rlc3,[modelName '/LCL_L1'], 'Position',[255 145 335 195], ...
    'component_structure','ee.enum.rlc.structure.SeriesRL', ...
    'R','G.filter.R1_ohm','L','G.filter.L1_H');
add_block(rlc3,[modelName '/LCL_L2'], 'Position',[365 145 445 195], ...
    'component_structure','ee.enum.rlc.structure.SeriesRL', ...
    'R','G.filter.R2_ohm','L','G.filter.L2_H');
add_block(rlc3,[modelName '/LCL_Damped_C'], 'Position',[320 235 400 285], ...
    'component_structure','ee.enum.rlc.structure.SeriesRC', ...
    'R','G.filter.Rd_ohm','C','G.filter.C_F');
add_block(gnd3,[modelName '/Filter_Ground'], 'Position',[425 245 455 275]);
add_block(xfmr3,[modelName '/T_BESS_0p69_10kV'], 'Position',[490 125 600 215], ...
    'SRated','G.transformer.S_VA','FRated','G.f0_Hz', ...
    'VRated1','G.ac.Vll_low_V','VRated2','G.ac.Vll_high_V', ...
    'Winding1Connection','ee.enum.windingconnection.delta1', ...
    'Winding2Connection','ee.enum.windingconnection.Yg', ...
    'pu_Rw1','G.transformer.pu_Rw1','pu_Rw2','G.transformer.pu_Rw2', ...
    'leakage_reactance_option','ee.enum.transformer_leakage.include', ...
    'pu_Xl1','G.transformer.pu_Xl1','pu_Xl2','G.transformer.pu_Xl2');
add_block(pq3,[modelName '/BESS_PQ_Sensor'], 'Position',[645 140 735 200]);
add_block(cpl3,[modelName '/Adjusted_Island_Load'], 'Position',[790 135 900 205], ...
    'FRated','G.f0_Hz','active_power','G.load.P_W','active_power_unit','W', ...
    'reactive_power','G.load.Q_var','reactive_power_unit','V*A', ...
    'Vline_rms_min','0.70*G.ac.Vll_high_V', ...
    'Vline_rms_ini','G.ac.Vll_high_V');
add_block('nesl_utility/Solver Configuration',[modelName '/Solver Configuration'], ...
    'Position',[650 55 710 105]);

% P/Q physical-to-Simulink measurements.
add_block(pss,[modelName '/P_to_Simulink'],'Position',[650 315 750 345],'Unit','W');
add_block(pss,[modelName '/Q_to_Simulink'],'Position',[650 370 750 400],'Unit','W');
add_block('simulink/Continuous/Transfer Fcn',[modelName '/P_Filter'], ...
    'Position',[790 310 880 350],'Numerator','1', ...
    'Denominator','[G.control.P_filter_s 1]');
add_block('simulink/Continuous/Transfer Fcn',[modelName '/Q_Filter'], ...
    'Position',[790 365 880 405],'Numerator','1', ...
    'Denominator','[G.control.Q_filter_s 1]');

% P-f droop: phase shift integrates 2*pi*(f-f0).
add_block('simulink/Math Operations/Gain',[modelName '/P_f_Droop'], ...
    'Position',[925 300 1035 340], ...
    'Gain','-2*pi*G.control.mp_Hz_per_W');
add_block('simulink/Continuous/Integrator',[modelName '/Phase_Integrator'], ...
    'Position',[1080 300 1120 340],'InitialCondition','pi/6');
add_block(sps,[modelName '/Phase_to_PS'], 'Position',[1160 295 1260 345], ...
    'Unit','rad','FilteringAndDerivatives','zero');

% Q-V droop around 690 V with 0.90-1.10 pu clamps.
add_block('simulink/Math Operations/Gain',[modelName '/Q_V_Droop'], ...
    'Position',[925 365 1035 405],'Gain','-G.control.nq_V_per_var');
add_block('simulink/Sources/Constant',[modelName '/V0_690V'], ...
    'Position',[915 430 965 460],'Value','G.ac.Vll_low_V');
add_block('simulink/Math Operations/Sum',[modelName '/V_Command_Sum'], ...
    'Position',[1080 380 1110 430],'Inputs','++');
add_block('simulink/Discontinuities/Saturation',[modelName '/V_Command_Limit'], ...
    'Position',[1140 380 1210 430], ...
    'UpperLimit','1.10*G.ac.Vll_low_V','LowerLimit','0.90*G.ac.Vll_low_V');
add_block(sps,[modelName '/Voltage_to_PS'], 'Position',[1250 375 1350 425], ...
    'Unit','V','FilteringAndDerivatives','zero');

% Frequency and SOC monitoring.
add_block('simulink/Math Operations/Gain',[modelName '/Frequency_Droop_Hz'], ...
    'Position',[925 485 1035 525],'Gain','-G.control.mp_Hz_per_W');
add_block('simulink/Sources/Constant',[modelName '/f0_50Hz'], ...
    'Position',[925 545 975 575],'Value','G.f0_Hz');
add_block('simulink/Math Operations/Sum',[modelName '/Frequency_Hz'], ...
    'Position',[1080 495 1110 545],'Inputs','++');
add_block('simulink/Math Operations/Gain',[modelName '/SOC_Rate'], ...
    'Position',[925 600 1035 640],'Gain','-1/(G.bess.E_Wh*3600)');
add_block('simulink/Continuous/Integrator',[modelName '/SOC'], ...
    'Position',[1080 600 1120 640],'InitialCondition','G.bess.SOC0', ...
    'LimitOutput','on','UpperSaturationLimit','G.bess.SOC_max', ...
    'LowerSaturationLimit','G.bess.SOC_min');

add_block('simulink/Sources/Clock',[modelName '/Time'], 'Position',[925 680 955 710]);
add_block('simulink/Signal Routing/Mux',[modelName '/Result_Mux'], ...
    'Position',[1240 500 1245 715],'Inputs','7');
add_block('simulink/Sinks/To Workspace',[modelName '/GFM_Results'], ...
    'Position',[1300 585 1410 625],'VariableName','gfm_result', ...
    'SaveFormat','Array','MaxDataPoints','inf');

% Physical connections.
connectp(modelName,'BESS_GFM_Controlled_Source','LConn',3,'Source_Neutral','LConn',1);
connectp(modelName,'BESS_GFM_Controlled_Source','RConn',1,'LCL_L1','LConn',1);
connectp(modelName,'LCL_L1','RConn',1,'LCL_L2','LConn',1);
branchp(modelName,porth([modelName '/LCL_L1'],'RConn',1), ...
    porth([modelName '/LCL_Damped_C'],'LConn',1));
connectp(modelName,'LCL_Damped_C','RConn',1,'Filter_Ground','LConn',1);
connectp(modelName,'LCL_L2','RConn',1,'T_BESS_0p69_10kV','LConn',1);
connectp(modelName,'T_BESS_0p69_10kV','RConn',1,'BESS_PQ_Sensor','LConn',1);
connectp(modelName,'BESS_PQ_Sensor','RConn',1,'Adjusted_Island_Load','LConn',1);
branchp(modelName,porth([modelName '/BESS_PQ_Sensor'],'RConn',1), ...
    porth([modelName '/Solver Configuration'],'RConn',1));
% Power Sensor physical outputs are P then Q in the LConn handle list.
add_line(modelName,porth([modelName '/BESS_PQ_Sensor'],'LConn',2), ...
    porth([modelName '/P_to_Simulink'],'LConn',1),'autorouting','on');
add_line(modelName,porth([modelName '/BESS_PQ_Sensor'],'LConn',3), ...
    porth([modelName '/Q_to_Simulink'],'LConn',1),'autorouting','on');
add_line(modelName,porth([modelName '/Voltage_to_PS'],'RConn',1), ...
    porth([modelName '/BESS_GFM_Controlled_Source'],'LConn',1),'autorouting','on');
add_line(modelName,porth([modelName '/Phase_to_PS'],'RConn',1), ...
    porth([modelName '/BESS_GFM_Controlled_Source'],'LConn',2),'autorouting','on');

% Simulink control wiring.
add_line(modelName,'P_to_Simulink/1','P_Filter/1','autorouting','on');
add_line(modelName,'Q_to_Simulink/1','Q_Filter/1','autorouting','on');
add_line(modelName,'P_Filter/1','P_f_Droop/1','autorouting','on');
add_line(modelName,'P_f_Droop/1','Phase_Integrator/1','autorouting','on');
add_line(modelName,'Phase_Integrator/1','Phase_to_PS/1','autorouting','on');
add_line(modelName,'Q_Filter/1','Q_V_Droop/1','autorouting','on');
add_line(modelName,'Q_V_Droop/1','V_Command_Sum/1','autorouting','on');
add_line(modelName,'V0_690V/1','V_Command_Sum/2','autorouting','on');
add_line(modelName,'V_Command_Sum/1','V_Command_Limit/1','autorouting','on');
add_line(modelName,'V_Command_Limit/1','Voltage_to_PS/1','autorouting','on');
add_line(modelName,'P_Filter/1','Frequency_Droop_Hz/1','autorouting','on');
add_line(modelName,'Frequency_Droop_Hz/1','Frequency_Hz/1','autorouting','on');
add_line(modelName,'f0_50Hz/1','Frequency_Hz/2','autorouting','on');
add_line(modelName,'P_Filter/1','SOC_Rate/1','autorouting','on');
add_line(modelName,'SOC_Rate/1','SOC/1','autorouting','on');

signals = {'Time/1','P_Filter/1','Q_Filter/1','Frequency_Hz/1', ...
    'V_Command_Limit/1','SOC/1','Phase_Integrator/1'};
for k=1:numel(signals)
    add_line(modelName,signals{k},sprintf('Result_Mux/%d',k),'autorouting','on');
end
add_line(modelName,'Result_Mux/1','GFM_Results/1','autorouting','on');

set_param(modelName,'Solver','ode23t','StopTime','0.5','MaxStep','2e-5', ...
    'SimscapeLogType','none','ReturnWorkspaceOutputs','on');
set_param(modelName,'InitFcn', ...
    "run(fullfile(fileparts(get_param(bdroot,'FileName')),'..','scripts','init_bess_gfm_stage.m'));");
note=Simulink.Annotation(modelName,sprintf([ ...
    'BESS-GFM physical source-equivalent stage only\n' ...
    'Rating: 2.5 MW / 2 MWh, 1200 V battery; PCS/transformer: 3.15 MVA\n' ...
    'Island load: 1.5 MW + j0.30 Mvar at 10 kV\n' ...
    'P-f droop: 0.5 Hz / 2.5 MW; Q-V droop: 5%% / 2.5 Mvar\n' ...
    'PV and wind are intentionally not present or modified in this stage.']));
note.Position=[70 760 720 860];
set_param(modelName,'ZoomFactor','FitSystem');
save_system(modelName,modelFile);
set_param(modelName,'SimulationCommand','update');
fprintf('BESS_GFM_UPDATE_OK=1\n');
try, print(['-s' modelName],'-dpng',pngFile); catch ME, fprintf('%s\n',ME.message); end
save_system(modelName,modelFile); close_system(modelName,0);
fprintf('BESS_GFM_MODEL=%s\n',modelFile);

function h=porth(block,side,index)
p=get_param(block,'PortHandles'); h=p.(side)(index);
end
function connectp(model,a,sa,ia,b,sb,ib)
add_line(model,porth([model '/' a],sa,ia),porth([model '/' b],sb,ib),'autorouting','on');
end
function branchp(model,a,b)
add_line(model,a,b,'autorouting','on');
end
