% Build the R3 control-oriented coordination validation model.
% R2 remains the physical-network architecture model. R3 validates the
% supervisory/GFM-GFL power-sharing logic before detailed VSC integration.

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(scriptDir);
run(fullfile(scriptDir, 'init_10kv_architecture.m'));

modelName = 'PV_Wind_BESS_Coordination_R3';
modelFile = fullfile(projectRoot, 'build', [modelName '.slx']);
pngFile = fullfile(projectRoot, 'build', [modelName '.png']);
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
new_system(modelName);
open_system(modelName);

add_block('simulink/Sources/Clock', [modelName '/Simulation_Time'], ...
    'Position', [70 160 100 190]);
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [modelName '/Wind_PV_BESS_Coordination'], ...
    'Position', [190 90 470 260]);
add_block('simulink/Sinks/To Workspace', [modelName '/Coordination_Results'], ...
    'Position', [570 145 700 195], 'VariableName', 'coord', ...
    'SaveFormat', 'Array', 'MaxDataPoints', 'inf');
add_block('simulink/Sinks/Scope', [modelName '/Coordination_Scope'], ...
    'Position', [570 235 700 285]);

add_line(modelName, 'Simulation_Time/1', 'Wind_PV_BESS_Coordination/1', ...
    'autorouting', 'on');
add_line(modelName, 'Wind_PV_BESS_Coordination/1', 'Coordination_Results/1', ...
    'autorouting', 'on');
add_line(modelName, 'Wind_PV_BESS_Coordination/1', 'Coordination_Scope/1', ...
    'autorouting', 'on');

rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', ...
    'Path', [modelName '/Wind_PV_BESS_Coordination']);
chart.Script = sprintf([ ...
    'function y = fcn(t)\n' ...
    '%% Control-oriented wind-PV-BESS island coordination model.\n' ...
    '%% y = [t grid f_Hz V_pu Pbess_MW Pgrid_MW Ppv_MW Pwind_MW Pload_MW SOC Qbess_Mvar]\n' ...
    '%%#codegen\n' ...
    'persistent fpu vpu pbess_pu soc\n' ...
    'Ts = 1e-3; Sbase = 10e6; Ebat_J = 4e6*3600;\n' ...
    'H = 2.0; Hq = 0.20; mp = 0.01; nq = 0.10; Tp = 0.05;\n' ...
    'Pmax = 0.50; Smax = 0.63; Tgrid = 0.02; Tvgrid = 0.02;\n' ...
    'if isempty(fpu)\n' ...
    '    fpu = 1.0; vpu = 1.0; pbess_pu = 0.0; soc = 0.60;\n' ...
    'end\n' ...
    'grid = double(t < 1.0);\n' ...
    'if t < 2.0, ppv = 0.30; else, ppv = 0.10; end\n' ...
    'if t < 4.0, pwind = 0.25; else, pwind = 0.15; end\n' ...
    'if t < 3.0, pload = 0.50; qload = 0.10; else, pload = 0.60; qload = 0.15; end\n' ...
    'qpv = ppv*tan(acos(0.90));\n' ...
    'pref = min(max((1.0-fpu)/mp, -Pmax), Pmax);\n' ...
    'if soc <= 0.20 && pref > 0.0, pref = 0.0; end\n' ...
    'if soc >= 0.90 && pref < 0.0, pref = 0.0; end\n' ...
    'pbess_pu = pbess_pu + Ts*(pref-pbess_pu)/Tp;\n' ...
    'pimb = ppv + pwind + pbess_pu - pload;\n' ...
    'if grid > 0.5\n' ...
    '    pgrid = -pimb;\n' ...
    '    df = (1.0-fpu)/Tgrid;\n' ...
    'else\n' ...
    '    pgrid = 0.0;\n' ...
    '    df = pimb/(2.0*H);\n' ...
    'end\n' ...
    'fpu = fpu + Ts*df;\n' ...
    'qcap = sqrt(max(Smax*Smax-pbess_pu*pbess_pu, 0.0));\n' ...
    'qbess = min(max((1.0-vpu)/nq, -qcap), qcap);\n' ...
    'qimb = qpv + qbess - qload;\n' ...
    'if grid > 0.5\n' ...
    '    dv = (1.0-vpu)/Tvgrid;\n' ...
    'else\n' ...
    '    dv = qimb/(2.0*Hq);\n' ...
    'end\n' ...
    'vpu = vpu + Ts*dv;\n' ...
    'soc = min(max(soc - Ts*pbess_pu*Sbase/Ebat_J, 0.0), 1.0);\n' ...
    'y = [t,grid,50.0*fpu,vpu,pbess_pu*Sbase/1e6,pgrid*Sbase/1e6, ...\n' ...
    '     ppv*Sbase/1e6,pwind*Sbase/1e6,pload*Sbase/1e6,soc, ...\n' ...
    '     qbess*Sbase/1e6];\n' ...
    'end\n']);

set_param(modelName, 'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', 'FixedStep', '1e-3', ...
    'StopTime', '5', 'ReturnWorkspaceOutputs', 'on');

note = Simulink.Annotation(modelName, sprintf([ ...
    'R3 control-oriented AC-coupled coordination validation\n' ...
    '0-1 s: grid-connected; at 1 s: islanding\n' ...
    '2 s: PV 3 -> 1 MW; 3 s: load 5 -> 6 MW; 4 s: wind 2.5 -> 1.5 MW\n' ...
    'BESS: 5 MW / 4 MWh GFM, P-f and Q-V droop, P/S/SOC limits\n' ...
    'Outputs: t, grid, f, V, Pbess, Pgrid, Ppv, Pwind, Pload, SOC, Qbess']));
note.Position = [70 330 760 440];

set_param(modelName, 'ZoomFactor', 'FitSystem');
save_system(modelName, modelFile);
set_param(modelName, 'SimulationCommand', 'update');
fprintf('R3_UPDATE_OK=1\n');
try
    print(['-s' modelName], '-dpng', pngFile);
    fprintf('R3_MODEL_PNG=%s\n', pngFile);
catch ME
    fprintf('R3_MODEL_PNG_EXPORT_OK=0\n%s\n', ME.message);
end
save_system(modelName, modelFile);
close_system(modelName, 0);
fprintf('R3_MODEL_FILE=%s\n', modelFile);
