% Build an R2026a-native Simscape Electrical architecture model.
% The converter terminals are represented by three-phase controlled-source
% equivalents for architecture and power-flow/transient integration checks.

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(scriptDir);
run(fullfile(scriptDir, 'init_10kv_architecture.m'));

modelName = 'PV_Wind_BESS_10kV_ACCoupled_R2026a';
modelFile = fullfile(projectRoot, 'build', [modelName '.slx']);
if ~exist(fullfile(projectRoot, 'build'), 'dir')
    mkdir(fullfile(projectRoot, 'build'));
end
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
new_system(modelName);
open_system(modelName);
load_system('ee_lib');
load_system('simscape');

src3 = sprintf('ee_lib/Sources/Voltage\nSource\n(Three-Phase)');
eref = 'fl_lib/Electrical/Electrical Elements/Electrical Reference';
gnd3 = sprintf('ee_lib/Connectors &\nReferences/Grounded Neutral\n(Three-Phase)');
rlc3 = 'ee_lib/Passive/RLC Assemblies/RLC (Three-Phase)';
xfmr3 = sprintf('ee_lib/Passive/Transformers/Two-Winding\nTransformer\n(Three-Phase)');
cpl3 = 'ee_lib/Passive/Constant Power Load (Three-Phase)';
solver = 'nesl_utility/Solver Configuration';

% PV grid-following inverter equivalent. The actual PV array connects
% directly to its own DC link; Vmpp is designed near P.pv.vdc_ref_V.
add_block(src3, [modelName '/PV_GFL_PCS_690V'], 'Position', [70 70 150 130], ...
    'vline_rms', 'P.base.V690_V', 'freq', 'P.meta.frequency_Hz', ...
    'shift', '30', 'SShortCircuit', '20*P.rating.unit_converter_VA', 'XR', '10');
add_block(eref, [modelName '/PV_Neutral'], 'Position', [25 85 55 115]);
add_block(rlc3, [modelName '/PV_LCL_series'], 'Position', [190 75 270 125], ...
    'component_structure', 'ee.enum.rlc.structure.SeriesRL', ...
    'R', 'P.filter.R1_ohm', 'L', 'P.filter.L1_H');
add_block(rlc3, [modelName '/PV_LCL_grid_inductor'], 'Position', [290 75 370 125], ...
    'component_structure', 'ee.enum.rlc.structure.SeriesRL', ...
    'R', 'P.filter.R2_ohm', 'L', 'P.filter.L2_H');
add_block(rlc3, [modelName '/PV_LCL_damped_C'], 'Position', [255 135 335 185], ...
    'component_structure', 'ee.enum.rlc.structure.SeriesRC', ...
    'R', 'P.filter.Rd_ohm', 'C', 'P.filter.C_F');
add_block(gnd3, [modelName '/PV_Filter_Ground'], 'Position', [360 145 390 175]);
add_block(xfmr3, [modelName '/T_PV_0p69_10kV'], 'Position', [410 60 515 140], ...
    'SRated', 'P.transformer.unit.S_VA', 'FRated', 'P.meta.frequency_Hz', ...
    'VRated1', 'P.transformer.unit.Vlow_V', 'VRated2', 'P.transformer.unit.Vhigh_V', ...
    'Winding1Connection', 'ee.enum.windingconnection.delta1', ...
    'Winding2Connection', 'ee.enum.windingconnection.Yg', ...
    'pu_Rw1', 'P.transformer.unit.pu_Rw1', 'pu_Rw2', 'P.transformer.unit.pu_Rw2', ...
    'leakage_reactance_option', 'ee.enum.transformer_leakage.include', ...
    'pu_Xl1', 'P.transformer.unit.pu_Xl1', 'pu_Xl2', 'P.transformer.unit.pu_Xl2');
add_block(rlc3, [modelName '/PV_10kV_Cable'], 'Position', [550 75 630 125], ...
    'component_structure', 'ee.enum.rlc.structure.SeriesRL', ...
    'R', 'P.line.pv.R_ohm', 'L', 'P.line.pv.L_H');

% BESS grid-forming inverter equivalent. The 1200 V battery reaches its
% separate inverter DC link through a bidirectional DC/DC converter.
add_block(src3, [modelName '/BESS_GFM_PCS_690V'], 'Position', [70 245 150 305], ...
    'vline_rms', 'P.base.V690_V', 'freq', 'P.meta.frequency_Hz', ...
    'shift', '30', 'SShortCircuit', '20*P.rating.unit_converter_VA', 'XR', '10');
add_block(eref, [modelName '/BESS_Neutral'], 'Position', [25 260 55 290]);
add_block(rlc3, [modelName '/BESS_LCL_series'], 'Position', [190 250 270 300], ...
    'component_structure', 'ee.enum.rlc.structure.SeriesRL', ...
    'R', 'P.filter.R1_ohm', 'L', 'P.filter.L1_H');
add_block(rlc3, [modelName '/BESS_LCL_grid_inductor'], 'Position', [290 250 370 300], ...
    'component_structure', 'ee.enum.rlc.structure.SeriesRL', ...
    'R', 'P.filter.R2_ohm', 'L', 'P.filter.L2_H');
add_block(rlc3, [modelName '/BESS_LCL_damped_C'], 'Position', [255 310 335 360], ...
    'component_structure', 'ee.enum.rlc.structure.SeriesRC', ...
    'R', 'P.filter.Rd_ohm', 'C', 'P.filter.C_F');
add_block(gnd3, [modelName '/BESS_Filter_Ground'], 'Position', [360 320 390 350]);
add_block(xfmr3, [modelName '/T_BESS_0p69_10kV'], 'Position', [410 235 515 315], ...
    'SRated', 'P.transformer.unit.S_VA', 'FRated', 'P.meta.frequency_Hz', ...
    'VRated1', 'P.transformer.unit.Vlow_V', 'VRated2', 'P.transformer.unit.Vhigh_V', ...
    'Winding1Connection', 'ee.enum.windingconnection.delta1', ...
    'Winding2Connection', 'ee.enum.windingconnection.Yg', ...
    'pu_Rw1', 'P.transformer.unit.pu_Rw1', 'pu_Rw2', 'P.transformer.unit.pu_Rw2', ...
    'leakage_reactance_option', 'ee.enum.transformer_leakage.include', ...
    'pu_Xl1', 'P.transformer.unit.pu_Xl1', 'pu_Xl2', 'P.transformer.unit.pu_Xl2');
add_block(rlc3, [modelName '/BESS_10kV_Cable'], 'Position', [550 250 630 300], ...
    'component_structure', 'ee.enum.rlc.structure.SeriesRL', ...
    'R', 'P.line.bess.R_ohm', 'L', 'P.line.bess.L_H');

% Full-converter wind branch.
add_block(src3, [modelName '/Wind_PCS_690V'], 'Position', [70 420 150 480], ...
    'vline_rms', 'P.base.V690_V', 'freq', 'P.meta.frequency_Hz', ...
    'shift', '30', 'SShortCircuit', '20*P.rating.unit_converter_VA', 'XR', '10');
add_block(eref, [modelName '/Wind_Neutral'], 'Position', [25 435 55 465]);
add_block(rlc3, [modelName '/Wind_LCL_series'], 'Position', [190 425 270 475], ...
    'component_structure', 'ee.enum.rlc.structure.SeriesRL', ...
    'R', 'P.filter.R1_ohm', 'L', 'P.filter.L1_H');
add_block(rlc3, [modelName '/Wind_LCL_grid_inductor'], 'Position', [290 425 370 475], ...
    'component_structure', 'ee.enum.rlc.structure.SeriesRL', ...
    'R', 'P.filter.R2_ohm', 'L', 'P.filter.L2_H');
add_block(rlc3, [modelName '/Wind_LCL_damped_C'], 'Position', [255 485 335 535], ...
    'component_structure', 'ee.enum.rlc.structure.SeriesRC', ...
    'R', 'P.filter.Rd_ohm', 'C', 'P.filter.C_F');
add_block(gnd3, [modelName '/Wind_Filter_Ground'], 'Position', [360 495 390 525]);
add_block(xfmr3, [modelName '/T_Wind_0p69_10kV'], 'Position', [410 410 515 490], ...
    'SRated', 'P.transformer.unit.S_VA', 'FRated', 'P.meta.frequency_Hz', ...
    'VRated1', 'P.transformer.unit.Vlow_V', 'VRated2', 'P.transformer.unit.Vhigh_V', ...
    'Winding1Connection', 'ee.enum.windingconnection.delta1', ...
    'Winding2Connection', 'ee.enum.windingconnection.Yg', ...
    'pu_Rw1', 'P.transformer.unit.pu_Rw1', 'pu_Rw2', 'P.transformer.unit.pu_Rw2', ...
    'leakage_reactance_option', 'ee.enum.transformer_leakage.include', ...
    'pu_Xl1', 'P.transformer.unit.pu_Xl1', 'pu_Xl2', 'P.transformer.unit.pu_Xl2');
add_block(rlc3, [modelName '/Wind_10kV_Cable'], 'Position', [550 425 630 475], ...
    'component_structure', 'ee.enum.rlc.structure.SeriesRL', ...
    'R', 'P.line.wind.R_ohm', 'L', 'P.line.wind.L_H');

% Utility connection at 10 kV.
add_block(src3, [modelName '/Grid_10kV'], 'Position', [790 610 870 670], ...
    'vline_rms', 'P.grid.Vll_V', 'freq', 'P.meta.frequency_Hz', ...
    'SShortCircuit', 'P.grid.short_circuit_VA', 'XR', 'P.grid.XR');
add_block(eref, [modelName '/Grid_Neutral'], 'Position', [900 625 930 655]);
add_block(rlc3, [modelName '/Grid_10kV_Cable'], 'Position', [650 615 730 665], ...
    'component_structure', 'ee.enum.rlc.structure.SeriesRL', ...
    'R', 'P.line.grid.R_ohm', 'L', 'P.line.grid.L_H');

% Dedicated load-side transformer: remove this stage if the main load is truly 10 kV.
add_block(xfmr3, [modelName '/T_Load_10_0p4kV'], 'Position', [700 145 805 225], ...
    'SRated', 'P.transformer.load.S_VA', 'FRated', 'P.meta.frequency_Hz', ...
    'VRated1', 'P.transformer.load.Vhigh_V', 'VRated2', 'P.transformer.load.Vlow_V', ...
    'Winding1Connection', 'ee.enum.windingconnection.delta1', ...
    'Winding2Connection', 'ee.enum.windingconnection.Yg', ...
    'pu_Rw1', 'P.transformer.load.pu_Rw1', 'pu_Rw2', 'P.transformer.load.pu_Rw2', ...
    'leakage_reactance_option', 'ee.enum.transformer_leakage.include', ...
    'pu_Xl1', 'P.transformer.load.pu_Xl1', 'pu_Xl2', 'P.transformer.load.pu_Xl2');
add_block(cpl3, [modelName '/Main_Load_5MW_400V'], 'Position', [860 150 950 220], ...
    'FRated', 'P.meta.frequency_Hz', 'active_power', 'P.rating.main_load_W', ...
    'active_power_unit', 'W', 'reactive_power', '0', ...
    'Vline_rms_min', '0.7*P.base.V400_V', 'Vline_rms_ini', 'P.base.V400_V');

add_block(solver, [modelName '/Solver Configuration'], 'Position', [690 35 750 90]);

% Physical connections.
connect_ports(modelName, 'PV_GFL_PCS_690V', 'LConn', 1, 'PV_Neutral', 'LConn', 1);
connect_ports(modelName, 'PV_GFL_PCS_690V', 'RConn', 1, 'PV_LCL_series', 'LConn', 1);
connect_ports(modelName, 'PV_LCL_series', 'RConn', 1, 'PV_LCL_grid_inductor', 'LConn', 1);
branch_physical(modelName, physical_port([modelName '/PV_LCL_series'], 'RConn', 1), ...
    physical_port([modelName '/PV_LCL_damped_C'], 'LConn', 1));
connect_ports(modelName, 'PV_LCL_damped_C', 'RConn', 1, 'PV_Filter_Ground', 'LConn', 1);
connect_ports(modelName, 'PV_LCL_grid_inductor', 'RConn', 1, 'T_PV_0p69_10kV', 'LConn', 1);
connect_ports(modelName, 'T_PV_0p69_10kV', 'RConn', 1, 'PV_10kV_Cable', 'LConn', 1);

connect_ports(modelName, 'BESS_GFM_PCS_690V', 'LConn', 1, 'BESS_Neutral', 'LConn', 1);
connect_ports(modelName, 'BESS_GFM_PCS_690V', 'RConn', 1, 'BESS_LCL_series', 'LConn', 1);
connect_ports(modelName, 'BESS_LCL_series', 'RConn', 1, 'BESS_LCL_grid_inductor', 'LConn', 1);
branch_physical(modelName, physical_port([modelName '/BESS_LCL_series'], 'RConn', 1), ...
    physical_port([modelName '/BESS_LCL_damped_C'], 'LConn', 1));
connect_ports(modelName, 'BESS_LCL_damped_C', 'RConn', 1, 'BESS_Filter_Ground', 'LConn', 1);
connect_ports(modelName, 'BESS_LCL_grid_inductor', 'RConn', 1, 'T_BESS_0p69_10kV', 'LConn', 1);
connect_ports(modelName, 'T_BESS_0p69_10kV', 'RConn', 1, 'BESS_10kV_Cable', 'LConn', 1);

connect_ports(modelName, 'Wind_PCS_690V', 'LConn', 1, 'Wind_Neutral', 'LConn', 1);
connect_ports(modelName, 'Wind_PCS_690V', 'RConn', 1, 'Wind_LCL_series', 'LConn', 1);
connect_ports(modelName, 'Wind_LCL_series', 'RConn', 1, 'Wind_LCL_grid_inductor', 'LConn', 1);
branch_physical(modelName, physical_port([modelName '/Wind_LCL_series'], 'RConn', 1), ...
    physical_port([modelName '/Wind_LCL_damped_C'], 'LConn', 1));
connect_ports(modelName, 'Wind_LCL_damped_C', 'RConn', 1, 'Wind_Filter_Ground', 'LConn', 1);
connect_ports(modelName, 'Wind_LCL_grid_inductor', 'RConn', 1, 'T_Wind_0p69_10kV', 'LConn', 1);
connect_ports(modelName, 'T_Wind_0p69_10kV', 'RConn', 1, 'Wind_10kV_Cable', 'LConn', 1);

connect_ports(modelName, 'Grid_10kV_Cable', 'RConn', 1, 'Grid_10kV', 'RConn', 1);
connect_ports(modelName, 'Grid_10kV', 'LConn', 1, 'Grid_Neutral', 'LConn', 1);
connect_ports(modelName, 'T_Load_10_0p4kV', 'RConn', 1, 'Main_Load_5MW_400V', 'LConn', 1);

% Create the 10 kV bus, then branch the remaining devices and solver onto it.
pvOut = physical_port([modelName '/PV_10kV_Cable'], 'RConn', 1);
loadIn = physical_port([modelName '/T_Load_10_0p4kV'], 'LConn', 1);
add_line(modelName, pvOut, loadIn, 'autorouting', 'on');
branch_physical(modelName, pvOut, physical_port([modelName '/Wind_10kV_Cable'], 'RConn', 1));
branch_physical(modelName, pvOut, physical_port([modelName '/BESS_10kV_Cable'], 'RConn', 1));
branch_physical(modelName, pvOut, physical_port([modelName '/Grid_10kV_Cable'], 'LConn', 1));
branch_physical(modelName, pvOut, physical_port([modelName '/Solver Configuration'], 'RConn', 1));

set_param(modelName, 'Solver', 'ode23t', 'StopTime', '0.2', ...
    'MaxStep', '1e-4', 'SimscapeLogType', 'none');
initCommand = "run(fullfile(fileparts(get_param(bdroot,'FileName')),'..','scripts','init_10kv_architecture.m'));";
set_param(modelName, 'InitFcn', initCommand);

note = Simulink.Annotation(modelName, sprintf([ ...
    'R2026a native AC-coupled architecture model\n' ...
    'PV GFL: direct array/DC link %.1f V -> 690 V -> 0.69/10 kV\n' ...
    'BESS GFM: 1200 V battery -> bidirectional DC/DC -> %.1f V link -> 690 V -> 0.69/10 kV\n' ...
    'Wind GFL: full converter 690 V -> 0.69/10 kV\n' ...
    'PCC: 10 kV, 50 Hz; LV load: 10/0.4 kV\n' ...
    'Converter blocks are source equivalents in this architecture-stage model.'], ...
    P.pv.vdc_ref_V, P.bess.dc_link_ref_V));
note.Position = [60 590 610 710];

set_param(modelName, 'ZoomFactor', 'FitSystem');
save_system(modelName, modelFile);

try
    set_param(modelName, 'SimulationCommand', 'update');
    fprintf('MODEL_UPDATE_OK=1\n');
catch ME
    fprintf('MODEL_UPDATE_OK=0\n%s\n', getReport(ME, 'extended', 'hyperlinks', 'off'));
end
save_system(modelName, modelFile);
pngFile = fullfile(projectRoot, 'build', [modelName '.png']);
try
    print(['-s' modelName], '-dpng', pngFile);
    fprintf('MODEL_PNG=%s\n', pngFile);
catch ME
    fprintf('MODEL_PNG_EXPORT_OK=0\n%s\n', ME.message);
end
close_system(modelName, 0);
fprintf('MODEL_FILE=%s\n', modelFile);

function h = physical_port(block, side, index)
ph = get_param(block, 'PortHandles');
h = ph.(side)(index);
end

function connect_ports(modelName, blockA, sideA, indexA, blockB, sideB, indexB)
a = physical_port([modelName '/' blockA], sideA, indexA);
b = physical_port([modelName '/' blockB], sideB, indexB);
add_line(modelName, a, b, 'autorouting', 'on');
end

function branch_physical(modelName, existingPortHandle, portHandle)
add_line(modelName, existingPortHandle, portHandle, 'autorouting', 'on');
end
