% Build standalone BESS-GFM with battery equivalent, DC link and average VSC.
% No PV, wind, or existing integrated model is modified by this script.
scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(scriptDir);
run(fullfile(scriptDir,'init_bess_gfm_average_pcs.m'));

modelName = 'BESS_GFM_10kV_AveragePCS_R5';
modelFile = fullfile(projectRoot,'build',[modelName '.slx']);
pngFile = fullfile(projectRoot,'build',[modelName '.png']);
if bdIsLoaded(modelName), close_system(modelName,0); end
new_system(modelName); open_system(modelName);
load_system('ee_lib'); load_system('fl_lib'); load_system('simscape');
load_system('nesl_utility');

vsc3 = sprintf(['ee_lib/Semiconductors &\nConverters/Converters/' ...
    'Average-Value\nVoltage Source\nConverter\n(Three-Phase)']);
pq3 = sprintf('ee_lib/Sensors &\nTransducers/Power Sensor\n(Three-Phase)');
rlc3 = 'ee_lib/Passive/RLC Assemblies/RLC (Three-Phase)';
xfmr3 = sprintf('ee_lib/Passive/Transformers/Two-Winding\nTransformer\n(Three-Phase)');
cpl3 = 'ee_lib/Passive/Constant Power Load (Three-Phase)';
eref = 'fl_lib/Electrical/Electrical Elements/Electrical Reference';
gnd3 = sprintf('ee_lib/Connectors &\nReferences/Grounded Neutral\n(Three-Phase)');
sps = sprintf('nesl_utility/Simulink-PS\nConverter');
pss = sprintf('nesl_utility/PS-Simulink\nConverter');

% Battery Thevenin equivalent and DC link. Positive current means discharge.
add_block('fl_lib/Electrical/Electrical Sources/DC Voltage Source', ...
    [modelName '/Battery_OCV'],'Position',[70 155 120 225],'v0','G.dc.Vbattery_V');
add_block('fl_lib/Electrical/Electrical Sensors/Current Sensor', ...
    [modelName '/Battery_Current'],'Position',[155 135 215 185]);
add_block('fl_lib/Electrical/Electrical Elements/Resistor', ...
    [modelName '/Battery_Internal_R'],'Position',[250 135 315 185], ...
    'R','G.dc.Rbattery_ohm');
add_block('fl_lib/Electrical/Electrical Elements/Capacitor', ...
    [modelName '/DC_Link_C'],'Position',[350 225 410 285], ...
    'c','G.dc.Cdc_F','vc_specify','on','vc','G.dc.Vbattery_V');
add_block('fl_lib/Electrical/Electrical Sensors/Voltage Sensor', ...
    [modelName '/DC_Link_Voltage'],'Position',[440 225 500 285]);
add_block(eref,[modelName '/DC_Negative_Reference'],'Position',[270 300 300 330]);

% Bidirectional average-value VSC and AC plant.
add_block(vsc3,[modelName '/Bidirectional_Average_VSC'], ...
    'Position',[540 130 650 220], ...
    'input_option','ee.enum.converters.inputOption.ModWave', ...
    'frequency_option','ee.enum.converters.frequency.variable', ...
    'FRated','G.f0_Hz','krec','G.dc.Rbattery_ohm/10');
add_block(rlc3,[modelName '/LCL_L1'],'Position',[700 145 780 195], ...
    'component_structure','ee.enum.rlc.structure.SeriesRL', ...
    'R','G.filter.R1_ohm','L','G.filter.L1_H');
add_block(rlc3,[modelName '/LCL_L2'],'Position',[810 145 890 195], ...
    'component_structure','ee.enum.rlc.structure.SeriesRL', ...
    'R','G.filter.R2_ohm','L','G.filter.L2_H');
add_block(rlc3,[modelName '/LCL_Damped_C'],'Position',[770 240 850 290], ...
    'component_structure','ee.enum.rlc.structure.SeriesRC', ...
    'R','G.filter.Rd_ohm','C','G.filter.C_F');
add_block(gnd3,[modelName '/Filter_Ground'],'Position',[875 250 905 280]);
add_block(xfmr3,[modelName '/T_BESS_0p69_10kV'],'Position',[935 125 1045 215], ...
    'SRated','G.transformer.S_VA','FRated','G.f0_Hz', ...
    'VRated1','G.ac.Vll_low_V','VRated2','G.ac.Vll_high_V', ...
    'Winding1Connection','ee.enum.windingconnection.delta1', ...
    'Winding2Connection','ee.enum.windingconnection.Yg', ...
    'pu_Rw1','G.transformer.pu_Rw1','pu_Rw2','G.transformer.pu_Rw2', ...
    'leakage_reactance_option','ee.enum.transformer_leakage.include', ...
    'pu_Xl1','G.transformer.pu_Xl1','pu_Xl2','G.transformer.pu_Xl2');
add_block(pq3,[modelName '/BESS_PQ_Sensor'],'Position',[1090 140 1180 200]);
add_block(cpl3,[modelName '/Adjusted_Island_Load'],'Position',[1230 135 1340 205], ...
    'FRated','G.f0_Hz','active_power','G.load.P_W','active_power_unit','W', ...
    'reactive_power','G.load.Q_var','reactive_power_unit','V*A', ...
    'Vline_rms_min','0.70*G.ac.Vll_high_V','Vline_rms_ini','G.ac.Vll_high_V');
add_block('nesl_utility/Solver Configuration',[modelName '/Solver Configuration'], ...
    'Position',[1100 60 1160 105]);

% Measurements.
add_block(pss,[modelName '/P_to_Simulink'],'Position',[1090 335 1190 365],'Unit','W');
add_block(pss,[modelName '/Q_to_Simulink'],'Position',[1090 390 1190 420],'Unit','W');
add_block(pss,[modelName '/Vdc_to_Simulink'],'Position',[440 345 540 375],'Unit','V');
add_block(pss,[modelName '/Idc_to_Simulink'],'Position',[155 345 255 375],'Unit','A');
add_block('simulink/Continuous/State-Space',[modelName '/Vdc_Filter'], ...
    'Position',[560 405 650 445], ...
    'A','-1/G.control.Vdc_filter_s','B','1/G.control.Vdc_filter_s', ...
    'C','1','D','0','InitialCondition','G.dc.Vbattery_V');
add_block('simulink/Continuous/Transfer Fcn',[modelName '/P_Filter'], ...
    'Position',[1220 330 1310 370],'Numerator','1','Denominator','[G.control.P_filter_s 1]');
add_block('simulink/Continuous/Transfer Fcn',[modelName '/Q_Filter'], ...
    'Position',[1220 385 1310 425],'Numerator','1','Denominator','[G.control.Q_filter_s 1]');

% P-f droop produces absolute electrical angle for the converter modulation.
add_block('simulink/Math Operations/Gain',[modelName '/P_f_Droop_rad_s'], ...
    'Position',[1360 320 1470 360],'Gain','-2*pi*G.control.mp_Hz_per_W');
add_block('simulink/Sources/Constant',[modelName '/Omega0'], ...
    'Position',[1360 270 1420 300],'Value','G.w0_rad_s');
add_block('simulink/Math Operations/Sum',[modelName '/Omega_Command'], ...
    'Position',[1510 290 1540 340],'Inputs','++');
add_block('simulink/Continuous/Integrator',[modelName '/Electrical_Angle'], ...
    'Position',[1580 295 1620 335],'InitialCondition','pi/6');

% Q-V droop and modulation-depth calculation using measured DC-link voltage.
add_block('simulink/Math Operations/Gain',[modelName '/Q_V_Droop'], ...
    'Position',[1360 390 1470 430],'Gain','-G.control.nq_V_per_var');
add_block('simulink/Sources/Constant',[modelName '/V0_690V'], ...
    'Position',[1360 455 1420 485],'Value','G.ac.Vll_low_V');
add_block('simulink/Math Operations/Sum',[modelName '/V_Command_Sum'], ...
    'Position',[1510 405 1540 455],'Inputs','++');
add_block('simulink/Discontinuities/Saturation',[modelName '/V_Command_Limit'], ...
    'Position',[1580 410 1660 450], ...
    'UpperLimit','1.10*G.ac.Vll_low_V','LowerLimit','0.90*G.ac.Vll_low_V');
add_block('simulink/Math Operations/Gain',[modelName '/Vll_to_Modulation_Numerator'], ...
    'Position',[1695 405 1805 445],'Gain','G.dc.kmod');
add_block('simulink/Math Operations/Product',[modelName '/Divide_By_Vdc'], ...
    'Position',[1845 405 1880 455],'Inputs','*/');
add_block('simulink/Discontinuities/Saturation',[modelName '/Modulation_Limit'], ...
    'Position',[1915 410 1990 450], ...
    'UpperLimit','G.dc.modulation_max','LowerLimit','0');

% Balanced three-phase modulation wave mabc.
add_block('simulink/Signal Routing/Mux',[modelName '/Mod_Inputs'], ...
    'Position',[2030 320 2035 450],'Inputs','2');
add_block('simulink/User-Defined Functions/Fcn',[modelName '/m_a'], ...
    'Position',[2070 320 2180 350],'Expr','u(1)*sin(u(2))');
add_block('simulink/User-Defined Functions/Fcn',[modelName '/m_b'], ...
    'Position',[2070 370 2180 400],'Expr','u(1)*sin(u(2)-2*pi/3)');
add_block('simulink/User-Defined Functions/Fcn',[modelName '/m_c'], ...
    'Position',[2070 420 2180 450],'Expr','u(1)*sin(u(2)+2*pi/3)');
add_block('simulink/Signal Routing/Mux',[modelName '/m_abc'], ...
    'Position',[2220 320 2225 450],'Inputs','3');
add_block(sps,[modelName '/Modulation_to_PS'],'Position',[2260 350 2360 410], ...
    'Unit','1','FilteringAndDerivatives','zero');

% DC power, SOC, frequency, and result logging.
add_block('simulink/Math Operations/Product',[modelName '/Battery_DC_Power'], ...
    'Position',[590 345 630 385]);
add_block('simulink/Math Operations/Gain',[modelName '/SOC_Rate'], ...
    'Position',[680 345 790 385],'Gain','-1/(G.bess.E_Wh*3600)');
add_block('simulink/Continuous/Integrator',[modelName '/SOC'], ...
    'Position',[830 345 870 385],'InitialCondition','G.bess.SOC0', ...
    'LimitOutput','on','UpperSaturationLimit','G.bess.SOC_max', ...
    'LowerSaturationLimit','G.bess.SOC_min');
add_block('simulink/Math Operations/Gain',[modelName '/Frequency_Droop_Hz'], ...
    'Position',[1360 520 1470 560],'Gain','-G.control.mp_Hz_per_W');
add_block('simulink/Sources/Constant',[modelName '/f0_50Hz'], ...
    'Position',[1360 580 1420 610],'Value','G.f0_Hz');
add_block('simulink/Math Operations/Sum',[modelName '/Frequency_Hz'], ...
    'Position',[1510 530 1540 580],'Inputs','++');
add_block('simulink/Sources/Clock',[modelName '/Time'],'Position',[1640 520 1670 550]);
add_block('simulink/Signal Routing/Mux',[modelName '/Result_Mux'], ...
    'Position',[2050 500 2055 740],'Inputs','10');
add_block('simulink/Sinks/To Workspace',[modelName '/GFM_PCS_Results'], ...
    'Position',[2110 600 2220 640],'VariableName','gfm_pcs_result', ...
    'SaveFormat','Array','MaxDataPoints','inf');

% DC physical connections.
connectp(modelName,'Battery_OCV','LConn',1,'Battery_Current','LConn',1);
connectp(modelName,'Battery_Current','RConn',2,'Battery_Internal_R','LConn',1);
connectp(modelName,'Battery_Internal_R','RConn',1,'Bidirectional_Average_VSC','RConn',1);
branchp(modelName,porth([modelName '/Battery_Internal_R'],'RConn',1), ...
    porth([modelName '/DC_Link_C'],'LConn',1));
branchp(modelName,porth([modelName '/Battery_Internal_R'],'RConn',1), ...
    porth([modelName '/DC_Link_Voltage'],'LConn',1));
connectp(modelName,'Battery_OCV','RConn',1,'Bidirectional_Average_VSC','RConn',2);
branchp(modelName,porth([modelName '/Battery_OCV'],'RConn',1), ...
    porth([modelName '/DC_Link_C'],'RConn',1));
branchp(modelName,porth([modelName '/Battery_OCV'],'RConn',1), ...
    porth([modelName '/DC_Link_Voltage'],'RConn',2));
branchp(modelName,porth([modelName '/Battery_OCV'],'RConn',1), ...
    porth([modelName '/DC_Negative_Reference'],'LConn',1));
add_line(modelName,porth([modelName '/Battery_Current'],'RConn',1), ...
    porth([modelName '/Idc_to_Simulink'],'LConn',1),'autorouting','on');
add_line(modelName,porth([modelName '/DC_Link_Voltage'],'RConn',1), ...
    porth([modelName '/Vdc_to_Simulink'],'LConn',1),'autorouting','on');

% AC physical connections.
connectp(modelName,'Bidirectional_Average_VSC','LConn',2,'LCL_L1','LConn',1);
connectp(modelName,'LCL_L1','RConn',1,'LCL_L2','LConn',1);
branchp(modelName,porth([modelName '/LCL_L1'],'RConn',1), ...
    porth([modelName '/LCL_Damped_C'],'LConn',1));
connectp(modelName,'LCL_Damped_C','RConn',1,'Filter_Ground','LConn',1);
connectp(modelName,'LCL_L2','RConn',1,'T_BESS_0p69_10kV','LConn',1);
connectp(modelName,'T_BESS_0p69_10kV','RConn',1,'BESS_PQ_Sensor','LConn',1);
connectp(modelName,'BESS_PQ_Sensor','RConn',1,'Adjusted_Island_Load','LConn',1);
branchp(modelName,porth([modelName '/BESS_PQ_Sensor'],'RConn',1), ...
    porth([modelName '/Solver Configuration'],'RConn',1));
add_line(modelName,porth([modelName '/BESS_PQ_Sensor'],'LConn',2), ...
    porth([modelName '/P_to_Simulink'],'LConn',1),'autorouting','on');
add_line(modelName,porth([modelName '/BESS_PQ_Sensor'],'LConn',3), ...
    porth([modelName '/Q_to_Simulink'],'LConn',1),'autorouting','on');
add_line(modelName,porth([modelName '/Modulation_to_PS'],'RConn',1), ...
    porth([modelName '/Bidirectional_Average_VSC'],'LConn',1),'autorouting','on');

% Simulink control and monitoring connections.
add_line(modelName,'P_to_Simulink/1','P_Filter/1','autorouting','on');
add_line(modelName,'Q_to_Simulink/1','Q_Filter/1','autorouting','on');
add_line(modelName,'P_Filter/1','P_f_Droop_rad_s/1','autorouting','on');
add_line(modelName,'P_f_Droop_rad_s/1','Omega_Command/1','autorouting','on');
add_line(modelName,'Omega0/1','Omega_Command/2','autorouting','on');
add_line(modelName,'Omega_Command/1','Electrical_Angle/1','autorouting','on');
add_line(modelName,'Q_Filter/1','Q_V_Droop/1','autorouting','on');
add_line(modelName,'Q_V_Droop/1','V_Command_Sum/1','autorouting','on');
add_line(modelName,'V0_690V/1','V_Command_Sum/2','autorouting','on');
add_line(modelName,'V_Command_Sum/1','V_Command_Limit/1','autorouting','on');
add_line(modelName,'V_Command_Limit/1','Vll_to_Modulation_Numerator/1','autorouting','on');
add_line(modelName,'Vll_to_Modulation_Numerator/1','Divide_By_Vdc/1','autorouting','on');
add_line(modelName,'Vdc_to_Simulink/1','Vdc_Filter/1','autorouting','on');
add_line(modelName,'Vdc_Filter/1','Divide_By_Vdc/2','autorouting','on');
add_line(modelName,'Divide_By_Vdc/1','Modulation_Limit/1','autorouting','on');
add_line(modelName,'Modulation_Limit/1','Mod_Inputs/1','autorouting','on');
add_line(modelName,'Electrical_Angle/1','Mod_Inputs/2','autorouting','on');
for k=1:3, add_line(modelName,'Mod_Inputs/1',sprintf('m_%c/1','a'+k-1),'autorouting','on'); end
add_line(modelName,'m_a/1','m_abc/1','autorouting','on');
add_line(modelName,'m_b/1','m_abc/2','autorouting','on');
add_line(modelName,'m_c/1','m_abc/3','autorouting','on');
add_line(modelName,'m_abc/1','Modulation_to_PS/1','autorouting','on');
add_line(modelName,'Vdc_to_Simulink/1','Battery_DC_Power/1','autorouting','on');
add_line(modelName,'Idc_to_Simulink/1','Battery_DC_Power/2','autorouting','on');
add_line(modelName,'Battery_DC_Power/1','SOC_Rate/1','autorouting','on');
add_line(modelName,'SOC_Rate/1','SOC/1','autorouting','on');
add_line(modelName,'P_Filter/1','Frequency_Droop_Hz/1','autorouting','on');
add_line(modelName,'Frequency_Droop_Hz/1','Frequency_Hz/1','autorouting','on');
add_line(modelName,'f0_50Hz/1','Frequency_Hz/2','autorouting','on');

signals = {'Time/1','P_Filter/1','Q_Filter/1','Frequency_Hz/1', ...
    'V_Command_Limit/1','SOC/1','DC_Link_Voltage/1','Idc_to_Simulink/1', ...
    'Modulation_Limit/1','Battery_DC_Power/1'};
% DC_Link_Voltage is a physical block; log its converted Simulink signal.
signals{7} = 'Vdc_to_Simulink/1';
for k=1:numel(signals)
    add_line(modelName,signals{k},sprintf('Result_Mux/%d',k),'autorouting','on');
end
add_line(modelName,'Result_Mux/1','GFM_PCS_Results/1','autorouting','on');

set_param(modelName,'Solver','ode23t','StopTime','0.5','MaxStep','2e-5', ...
    'SimscapeLogType','none','ReturnWorkspaceOutputs','on');
set_param(modelName,'InitFcn', ...
    "run(fullfile(fileparts(get_param(bdroot,'FileName')),'..','scripts','init_bess_gfm_average_pcs.m'));" );
note = Simulink.Annotation(modelName,sprintf([ ...
    'Standalone BESS-GFM average PCS (PV/wind untouched)\n' ...
    '2.5 MW / 2.0 MWh battery; 3.15 MVA PCS and transformer\n' ...
    '1200 V battery direct DC link; 690 V / 10 kV AC interface\n' ...
    'Bidirectional average VSC, P-f and Q-V droop, modulation limit 0.98']));
note.Position = [80 760 780 850];
set_param(modelName,'ZoomFactor','FitSystem');
save_system(modelName,modelFile);
set_param(modelName,'SimulationCommand','update');
fprintf('BESS_GFM_AVERAGE_PCS_UPDATE_OK=1\n');
try, print(['-s' modelName],'-dpng',pngFile); catch ME, fprintf('%s\n',ME.message); end
save_system(modelName,modelFile); close_system(modelName,0);
fprintf('BESS_GFM_AVERAGE_PCS_MODEL=%s\n',modelFile);

function h=porth(block,side,index)
p=get_param(block,'PortHandles'); h=p.(side)(index);
end
function connectp(model,a,sa,ia,b,sb,ib)
add_line(model,porth([model '/' a],sa,ia),porth([model '/' b],sb,ib),'autorouting','on');
end
function branchp(model,a,b)
add_line(model,a,b,'autorouting','on');
end
