% Build BESS-only R7 with dynamic DC/DC control, current limits, virtual Z,
% and a physical 1 MW load-step branch. PV and wind remain untouched.
scriptDir=fileparts(mfilename('fullpath'));
projectRoot=fileparts(scriptDir);
run(fullfile(scriptDir,'build_bess_gfm_final_r6.m'));
sourceFile=fullfile(projectRoot,'build','BESS_GFM_10kV_Final_R6.slx');
modelName='BESS_GFM_10kV_Dynamic_R7';
modelFile=fullfile(projectRoot,'build',[modelName '.slx']);
pngFile=fullfile(projectRoot,'build',[modelName '.png']);
copyfile(sourceFile,modelFile,'f');
load_system(modelFile);
run(fullfile(scriptDir,'init_bess_gfm_dynamic_r7.m'));
set_param([modelName '/Vdc_Filter'],'InitialCondition','G.dc.Vdc_ref_V');
clear_input_line([modelName '/Divide_By_Vdc'],2);
add_block('simulink/Discontinuities/Saturation',[modelName '/Vdc_For_Modulation'], ...
    'Position',[870 400 950 440],'LowerLimit','500','UpperLimit','2000');
add_line(modelName,'Vdc_Filter/1','Vdc_For_Modulation/1','autorouting','on');
add_line(modelName,'Vdc_For_Modulation/1','Divide_By_Vdc/2','autorouting','on');

% Replace ideal voltage-command DC/DC with a duty-cycle behavioral converter.
% Explicit external L and C provide the dynamic energy-storage states.
dcdc=[modelName '/Bidirectional_1200_1500V_DCDC'];
set_param(dcdc, ...
    'implementation_option','ee.enum.converters.implementation.behavioral', ...
    'converter_type','ee.enum.converters.dcdctype.buckboost', ...
    'control_option','ee.enum.converters.controlinput.dutycycle', ...
    'efficiency_option','ee.enum.converters.efficiency.constant', ...
    'efficiency_fixed','G.dc.dcdc_efficiency_pct');
% Insert an explicit input inductor between the battery resistance and DC/DC.
clear_physical_line([modelName '/Battery_Internal_R'],'RConn',1);
add_block('fl_lib/Electrical/Electrical Elements/Inductor', ...
    [modelName '/DCDC_Input_Inductor'],'Position',[300 115 360 165], ...
    'l','G.dcdc.L_H','i_specify','on','i','G.dcdc.Iref_initial_A');
connectp(modelName,'Battery_Internal_R','RConn',1,'DCDC_Input_Inductor','LConn',1);
connectp(modelName,'DCDC_Input_Inductor','RConn',1, ...
    'Bidirectional_1200_1500V_DCDC','LConn',2);
branchp(modelName,porth([modelName '/Battery_Internal_R'],'RConn',1), ...
    porth([modelName '/Battery_Terminal_Voltage'],'LConn',1));
for b={'Vdc_1500V_Reference','DCDC_Vref_to_PS'}
    p=[modelName '/' b{1}]; if getSimulinkBlockHandle(p)>0, delete_block(p); end
end
clear_physical_line(dcdc,'LConn',1);

% Cascaded Vdc PI -> battery-current PI -> duty ratio.
add_block('simulink/Sources/Constant',[modelName '/Vdc_Reference'], ...
    'Position',[750 500 820 530],'Value','G.dc.Vdc_ref_V');
add_block('simulink/Math Operations/Sum',[modelName '/Vdc_Error'], ...
    'Position',[870 485 900 535],'Inputs','+-');
add_block('simulink/Math Operations/Gain',[modelName '/Vdc_Kp'], ...
    'Position',[940 470 1020 505],'Gain','G.dcdc.Kpv_A_per_V');
add_block('simulink/Math Operations/Gain',[modelName '/Vdc_Ki'], ...
    'Position',[940 525 1020 560],'Gain','G.dcdc.Kiv_A_per_Vs');
add_block('simulink/Continuous/Integrator',[modelName '/Vdc_PI_Integrator'], ...
    'Position',[1060 520 1100 560],'InitialCondition','0');
add_block('simulink/Math Operations/Sum',[modelName '/Battery_Current_Reference'], ...
    'Position',[1140 485 1170 545],'Inputs','+++');
add_block('simulink/Discontinuities/Saturation',[modelName '/DC_Current_Limit'], ...
    'Position',[1210 490 1300 530], ...
    'UpperLimit','G.dcdc.Iref_limit_A','LowerLimit','-G.dcdc.Iref_limit_A');
add_block('simulink/Continuous/State-Space',[modelName '/P_DC_Feedforward_Filter'], ...
    'Position',[900 590 1010 630], ...
    'A','-1/G.dcdc.power_ff_filter_s','B','1/G.dcdc.power_ff_filter_s', ...
    'C','1','D','0','InitialCondition','G.load.base_P_W');
add_block('simulink/Math Operations/Gain',[modelName '/P_to_Battery_Current_FF'], ...
    'Position',[1040 590 1130 630], ...
    'Gain','1/(G.dc.Vbattery_V*G.dc.dcdc_efficiency_pct/100)');
add_block('simulink/Math Operations/Sum',[modelName '/DC_Current_Error'], ...
    'Position',[1340 485 1370 535],'Inputs','+-');
add_block('simulink/Continuous/State-Space',[modelName '/Idc_Filter'], ...
    'Position',[1210 570 1300 610], ...
    'A','-1/G.dcdc.current_sensor_s','B','1/G.dcdc.current_sensor_s', ...
    'C','1','D','0','InitialCondition','G.dcdc.Iref_initial_A');
add_block('simulink/Math Operations/Gain',[modelName '/DC_Current_Kp'], ...
    'Position',[1410 465 1490 500],'Gain','G.dcdc.Kpi_duty_per_A');
add_block('simulink/Math Operations/Gain',[modelName '/DC_Current_Ki'], ...
    'Position',[1410 525 1490 560],'Gain','G.dcdc.Kii_duty_per_As');
add_block('simulink/Continuous/Integrator',[modelName '/DC_Current_PI_Integrator'], ...
    'Position',[1530 520 1570 560],'InitialCondition','0');
add_block('simulink/Sources/Constant',[modelName '/Duty_Feedforward'], ...
    'Position',[1510 430 1580 460],'Value','G.dcdc.duty_ff');
add_block('simulink/Math Operations/Sum',[modelName '/Duty_Command_Sum'], ...
    'Position',[1620 470 1650 535],'Inputs','+++');
add_block('simulink/Discontinuities/Saturation',[modelName '/Duty_Limit'], ...
    'Position',[1690 480 1770 525], ...
    'UpperLimit','G.dcdc.duty_max','LowerLimit','G.dcdc.duty_min');
sps=sprintf('nesl_utility/Simulink-PS\nConverter');
add_block(sps,[modelName '/Duty_to_PS'],'Position',[1810 475 1910 530], ...
    'Unit','1','FilteringAndDerivatives','zero');
add_line(modelName,'Vdc_Reference/1','Vdc_Error/1','autorouting','on');
add_line(modelName,'Vdc_Filter/1','Vdc_Error/2','autorouting','on');
add_line(modelName,'Vdc_Error/1','Vdc_Kp/1','autorouting','on');
add_line(modelName,'Vdc_Error/1','Vdc_Ki/1','autorouting','on');
add_line(modelName,'Vdc_Ki/1','Vdc_PI_Integrator/1','autorouting','on');
add_line(modelName,'Vdc_Kp/1','Battery_Current_Reference/1','autorouting','on');
add_line(modelName,'Vdc_PI_Integrator/1','Battery_Current_Reference/2','autorouting','on');
add_line(modelName,'P_to_Simulink/1','P_DC_Feedforward_Filter/1','autorouting','on');
add_line(modelName,'P_DC_Feedforward_Filter/1','P_to_Battery_Current_FF/1','autorouting','on');
add_line(modelName,'P_to_Battery_Current_FF/1','Battery_Current_Reference/3','autorouting','on');
add_line(modelName,'Battery_Current_Reference/1','DC_Current_Limit/1','autorouting','on');
add_line(modelName,'DC_Current_Limit/1','DC_Current_Error/1','autorouting','on');
add_line(modelName,'Idc_to_Simulink/1','Idc_Filter/1','autorouting','on');
add_line(modelName,'Idc_Filter/1','DC_Current_Error/2','autorouting','on');
add_line(modelName,'DC_Current_Error/1','DC_Current_Kp/1','autorouting','on');
add_line(modelName,'DC_Current_Error/1','DC_Current_Ki/1','autorouting','on');
add_line(modelName,'DC_Current_Ki/1','DC_Current_PI_Integrator/1','autorouting','on');
add_line(modelName,'DC_Current_Kp/1','Duty_Command_Sum/1','autorouting','on');
add_line(modelName,'DC_Current_PI_Integrator/1','Duty_Command_Sum/2','autorouting','on');
add_line(modelName,'Duty_Feedforward/1','Duty_Command_Sum/3','autorouting','on');
add_line(modelName,'Duty_Command_Sum/1','Duty_Limit/1','autorouting','on');
add_line(modelName,'Duty_Limit/1','Duty_to_PS/1','autorouting','on');
add_line(modelName,porth([modelName '/Duty_to_PS'],'RConn',1), ...
    porth(dcdc,'LConn',1),'autorouting','on');

% Balanced positive-sequence virtual-impedance approximation.
add_block('simulink/Signal Routing/Mux',[modelName '/Virtual_Z_Inputs'], ...
    'Position',[1340 610 1345 710],'Inputs','3');
add_block('simulink/User-Defined Functions/Fcn',[modelName '/Virtual_Impedance_dV'], ...
    'Position',[1390 630 1570 670], ...
    'Expr','(-G.control.Rvirt_ohm*u(1)+G.control.Xvirt_ohm*u(2))/u(3)');
set_param([modelName '/V_Command_Sum'],'Inputs','+++');
add_line(modelName,'P_Filter/1','Virtual_Z_Inputs/1','autorouting','on');
add_line(modelName,'Q_Filter/1','Virtual_Z_Inputs/2','autorouting','on');
add_line(modelName,'V0_690V/1','Virtual_Z_Inputs/3','autorouting','on');
add_line(modelName,'Virtual_Z_Inputs/1','Virtual_Impedance_dV/1','autorouting','on');
add_line(modelName,'Virtual_Impedance_dV/1','V_Command_Sum/3','autorouting','on');

% AC current estimation and 1.20 pu modulation limiter.
add_block('simulink/Signal Routing/Mux',[modelName '/AC_Current_Inputs'], ...
    'Position',[1740 610 1745 710],'Inputs','3');
add_block('simulink/User-Defined Functions/Fcn',[modelName '/AC_Current_RMS'], ...
    'Position',[1790 625 1960 665], ...
    'Expr','sqrt(u(1)^2+u(2)^2)/(sqrt(3)*u(3))');
add_block('simulink/User-Defined Functions/Fcn',[modelName '/AC_Current_Limit_Factor'], ...
    'Position',[1790 680 1960 720], ...
    'Expr','G.control.Iac_limit_A/(u(1)+1)');
add_block('simulink/Discontinuities/Saturation',[modelName '/AC_Current_Limit_Saturation'], ...
    'Position',[1980 685 2050 720],'UpperLimit','1','LowerLimit','0');
add_block('simulink/Math Operations/Product',[modelName '/Apply_AC_Current_Limit'], ...
    'Position',[2010 625 2050 675]);
clear_input_line([modelName '/Modulation_Limit'],1);
add_line(modelName,'P_Filter/1','AC_Current_Inputs/1','autorouting','on');
add_line(modelName,'Q_Filter/1','AC_Current_Inputs/2','autorouting','on');
add_line(modelName,'V_Command_Limit/1','AC_Current_Inputs/3','autorouting','on');
add_line(modelName,'AC_Current_Inputs/1','AC_Current_RMS/1','autorouting','on');
add_line(modelName,'AC_Current_RMS/1','AC_Current_Limit_Factor/1','autorouting','on');
add_line(modelName,'Divide_By_Vdc/1','Apply_AC_Current_Limit/1','autorouting','on');
add_line(modelName,'AC_Current_Limit_Factor/1','AC_Current_Limit_Saturation/1','autorouting','on');
add_line(modelName,'AC_Current_Limit_Saturation/1','Apply_AC_Current_Limit/2','autorouting','on');
add_line(modelName,'Apply_AC_Current_Limit/1','Modulation_Limit/1','autorouting','on');

% Physical 1 MW load step at the 10 kV bus.
cpl3='ee_lib/Passive/Constant Power Load (Three-Phase)';
cb3=sprintf('ee_lib/Switches & Breakers/Circuit Breaker\n(Three-Phase)');
add_block(cb3,[modelName '/Step_Load_Breaker'],'Position',[1240 245 1340 305], ...
    'control_port_option','ee.enum.controlport.ps');
add_block(cpl3,[modelName '/One_MW_Step_Load'],'Position',[1390 240 1500 310], ...
    'FRated','G.f0_Hz','active_power','G.load.step_P_W','active_power_unit','W', ...
    'reactive_power','G.load.step_Q_var','reactive_power_unit','V*A', ...
    'Vline_rms_min','0.70*G.ac.Vll_high_V','Vline_rms_ini','G.ac.Vll_high_V');
add_block('simulink/Sources/Step',[modelName '/Load_Step_Command'], ...
    'Position',[1030 245 1090 275],'Time','G.load.step_time_s', ...
    'Before','1','After','0');
add_block(sps,[modelName '/Load_Step_to_PS'],'Position',[1120 235 1220 285], ...
    'Unit','V','FilteringAndDerivatives','zero');
set_param([modelName '/Adjusted_Island_Load'], ...
    'active_power','G.load.base_P_W','reactive_power','G.load.base_Q_var');
branchp(modelName,porth([modelName '/BESS_PQ_Sensor'],'RConn',1), ...
    porth([modelName '/Step_Load_Breaker'],'LConn',2));
connectp(modelName,'Step_Load_Breaker','RConn',1,'One_MW_Step_Load','LConn',1);
add_line(modelName,'Load_Step_Command/1','Load_Step_to_PS/1','autorouting','on');
add_line(modelName,porth([modelName '/Load_Step_to_PS'],'RConn',1), ...
    porth([modelName '/Step_Load_Breaker'],'LConn',1),'autorouting','on');

% Extended R7 result vector.
add_block('simulink/Signal Routing/Mux',[modelName '/R7_Result_Mux'], ...
    'Position',[2130 500 2135 830],'Inputs','15');
add_block('simulink/Sinks/To Workspace',[modelName '/R7_Results'], ...
    'Position',[2190 640 2300 680],'VariableName','gfm_r7_result', ...
    'SaveFormat','Array','MaxDataPoints','inf');
r7signals={'Time/1','P_Filter/1','Q_Filter/1','Frequency_Hz/1', ...
    'V_Command_Limit/1','SOC/1','Vdc_to_Simulink/1','Idc_to_Simulink/1', ...
    'Modulation_Limit/1','Battery_DC_Power/1','Duty_Limit/1', ...
    'DC_Current_Limit/1','AC_Current_RMS/1','AC_Current_Limit_Saturation/1', ...
    'Load_Step_Command/1'};
for k=1:numel(r7signals)
    add_line(modelName,r7signals{k},sprintf('R7_Result_Mux/%d',k),'autorouting','on');
end
add_line(modelName,'R7_Result_Mux/1','R7_Results/1','autorouting','on');

set_param(modelName,'InitFcn', ...
    "run(fullfile(fileparts(get_param(bdroot,'FileName')),'..','scripts','init_bess_gfm_dynamic_r7.m'));" );
set_param(modelName,'StopTime','0.8','MaxStep','1e-5');
anns=find_system(modelName,'FindAll','on','Type','annotation');
for k=1:numel(anns),delete(anns(k));end
note=Simulink.Annotation(modelName,sprintf([ ...
    'R7 BESS-GFM dynamic controls only (PV/wind untouched)\n' ...
    'Finite-bandwidth 1500 V outer PI + battery-current inner PI\n' ...
    'DC limit 1.10 pu; AC limit 1.20 pu; virtual Z 0.02+j0.10 pu\n' ...
    'Physical load step: 4 MW -> 5 MW at 0.30 s']));
note.Position=[80 860 850 950];
save_system(modelName,modelFile);
set_param(modelName,'SimulationCommand','update');
fprintf('BESS_GFM_DYNAMIC_R7_UPDATE_OK=1\n');
try,print(['-s' modelName],'-dpng',pngFile);catch ME,fprintf('%s\n',ME.message);end
save_system(modelName,modelFile);close_system(modelName,0);
fprintf('BESS_GFM_DYNAMIC_R7_MODEL=%s\n',modelFile);

function h=porth(block,side,index)
p=get_param(block,'PortHandles');h=p.(side)(index);
end
function connectp(model,a,sa,ia,b,sb,ib)
add_line(model,porth([model '/' a],sa,ia),porth([model '/' b],sb,ib),'autorouting','on');
end
function branchp(model,a,b)
add_line(model,a,b,'autorouting','on');
end
function clear_input_line(block,index)
p=get_param(block,'PortHandles');h=get_param(p.Inport(index),'Line');
if h>0,delete_line(h);end
end
function clear_physical_line(block,side,index)
p=get_param(block,'PortHandles');h=get_param(p.(side)(index),'Line');
if h>0,delete_line(h);end
end
