% 5 MW PV-GFL commissioning base with a strong synchronous machine.
Base.Sn = 6.25e6;
Base.f = 50;
Base.omega = 2*pi*Base.f;
Base.Vll_lv = 690;
Base.Vll_hv = 10e3;
Base.I_lv = Base.Sn/(sqrt(3)*Base.Vll_lv);
Base.I_hv = Base.Sn/(sqrt(3)*Base.Vll_hv);
Base.Z_lv = Base.Vll_lv^2/Base.Sn;
Base.Z_hv = Base.Vll_hv^2/Base.Sn;
Base.Simulation.StopTime = 0.15;
Base.Simulation.MaxStep = 1e-5;

Converter.Sn = Base.Sn;
Converter.Vll = Base.Vll_lv;
Converter.Vdc_nom = 1500;
Converter.Cdc = 3.09e-3;
Converter.Cdc_esr = 5e-3;
Converter.fsw = 5e3;
Converter.Imax_pu = 1.10;
Converter.Imax = Converter.Imax_pu*Base.I_lv;
Converter.SwitchOnResistance = 1e-3;
Converter.OffConductance = 1e-6;
Converter.GateThresholdVoltage = 0.5;

Filter.R = 0.005*Base.Z_lv;
Filter.L = 0.08*Base.Z_lv/Base.omega;
Transformer.Sn = 6.3e6;
Transformer.f = Base.f;
Transformer.Vll_primary = Base.Vll_lv;
Transformer.Vll_secondary = Base.Vll_hv;
Transformer.R1_pu = 0.005;
Transformer.R2_pu = 0.005;
Transformer.X1_pu = 0.03;
Transformer.X2_pu = 0.03;
Transformer.Xm_pu = 500;

PV.SourceType = 'stiff DC source for GFL commissioning';
PV.Vdc = Converter.Vdc_nom;
PV.Pnom = 5e6;
PV.EnableDetailedPV = false;

Control.Ts = 1/(20*Converter.fsw);
Control.PWM.Ts = 1/Converter.fsw;
Control.PWM.GatesOff = zeros(1,6);
Control.PWM.CarrierFrequency = Converter.fsw;
Control.PWM.CarrierPeriod = 1/Control.PWM.CarrierFrequency;
Control.PWM.MaxStep = 1/(50*Control.PWM.CarrierFrequency);
Control.PWM.ModulationIndex = 2*sqrt(2)*Converter.Vll/(sqrt(3)*Converter.Vdc_nom);
Control.PWM.PhaseABC = [0,-2*pi/3,2*pi/3];
Control.PWM.SmokeStopTime = 2e-3;
Control.PWM.OperatingPointStopTime = 0.08;
Control.PLL.Kp = 60;
Control.PLL.Ki = 1400;
Control.PLL.Vbase = Base.Vll_hv;
Control.PLL.OmegaNominal = Base.omega;
Control.PLL.OmegaMin = 2*pi*45;
Control.PLL.OmegaMax = 2*pi*55;
Control.PLL.VoltagePrefilterHz = 200;
Control.PLL.Theta0 = -pi/2-atan(Base.f/Control.PLL.VoltagePrefilterHz);
Control.PLL.ValidationStopTime = 0.12;
Control.Measurement.PowerLPFHz = 100;
Control.Current.Kp = Filter.L*2*pi*150;
Control.Current.Ki = Filter.R*2*pi*150;
Control.Vdc.Kp = 0.5;
Control.Vdc.Ki = 25;
Control.Q.Kp = 0.2;
Control.Q.Ki = 10;

% Strong machine: 25 MVA is four times the PV PCS rating.  Its local
% 5 MW load lets the governor supply the balance while PV power is raised.
Grid.frequency = Base.f;
Grid.voltage = Base.Vll_hv;
GridTransformer.hv = Base.Vll_hv;
GridTransformer.lv = Base.Vll_hv;
GridTransformer.VA = 25e6;
GridTransformer.winding_resistance = 0.01;
GridTransformer.winding_lekage_reactance = 0.08;
GridTransformer.zero_sequence_reactance = 0.10;
SM.MVA = 25e6;
SM.Voltage = Base.Vll_hv;
SM.polepairs = 1;
SM.w_sm = Base.omega;
SM.field_current = 1300;
SM.Base_Torque_SM = SM.MVA/SM.w_sm;
SM.initial_torque = 0.20;
SM.initial_Pe = 5e6;
SM.initial_Qe = 0;
SM.stator_resistance = 0.003;
SM.lekage_reactance = 0.15;
SM.xd = 1.81; SM.xq = 1.76;
SM.xd_ = 0.30; SM.xq_ = 0.65;
SM.xd_dash = 0.23; SM.xq_dash = 0.25;
SM.Tdo_ = 8; SM.Tdo_dash = 0.03;
SM.Tqo_ = 1; SM.Tqo_dash = 0.07;
SM.inertia = 5.0;
SM.damping = 0.02;
SM.speed_reference = 1.0;
SM.droop_p = 5;
SM.load_reference_set_point = 0.20;
SM.governor_time_constant = 0.2;
SM.time_constsnt_steamchest = 0.3;
SM.P_load = 5e6;
SM.Q_load = 1.0e6;
SimulationTime = Base.Simulation.StopTime;
Ts = 5e-5;

assignin('base','Base',Base); assignin('base','Converter',Converter);
assignin('base','Filter',Filter); assignin('base','Transformer',Transformer);
assignin('base','PV',PV); assignin('base','Control',Control);
assignin('base','Grid',Grid); assignin('base','GridTransformer',GridTransformer);
assignin('base','SM',SM); assignin('base','SimulationTime',SimulationTime);
assignin('base','Ts',Ts);
