% Confirm that hierarchical packaging preserved the validated R7 behavior.
scriptDir=fileparts(mfilename('fullpath'));
projectRoot=fileparts(scriptDir);
run(fullfile(scriptDir,'init_bess_gfm_dynamic_r7.m'));
modelName='BESS_GFM_10kV_Readable_R8';
load_system(fullfile(projectRoot,'build',[modelName '.slx']));
required={ ...
    '01 BESS DC Source/02 Bidirectional DC-DC Control/Vdc_AW_Gain', ...
    '01 BESS DC Source/02 Bidirectional DC-DC Control/Duty_AW_Gain', ...
    '01 BESS DC Source/02 Bidirectional DC-DC Control/SOC_Discharge_Allowed', ...
    '01 BESS DC Source/02 Bidirectional DC-DC Control/SOC_Charge_Allowed', ...
    '01 BESS DC Source/02 Bidirectional DC-DC Control/DC_Current_Limit'};
for k=1:numel(required)
    assert(getSimulinkBlockHandle([modelName '/' required{k}])>0, ...
        'Missing R8 protection block: %s',required{k});
end
out=sim(modelName);
r=squeeze(out.get('gfm_r7_result'));
if size(r,2)~=15,r=r.';end
assert(size(r,2)==15 && all(isfinite(r),'all'),'R8 telemetry is invalid.');
t=r(:,1);pre=t>0.22&t<0.28;post=t>0.70;event=t>0.28;
a=mean(r(pre,:),1);b=mean(r(post,:),1);
assert(a(2)>3.90e6&&a(2)<4.10e6,'R8 pre-step power mismatch.');
assert(b(2)>4.90e6&&b(2)<5.15e6,'R8 post-step power mismatch.');
assert(min(r(event,7))>0.95*G.dc.Vdc_ref_V&& ...
    max(r(event,7))<1.05*G.dc.Vdc_ref_V,'R8 DC-link transient mismatch.');
assert(max(abs(r(event,8)))<G.dcdc.Imax_A,'R8 battery current limit failed.');
assert(mean(r(pre,14))>0.90&&mean(r(pre,14))<=1.01, ...
    'R8 AC current-limit telemetry route is missing.');
fprintf(['BESS_GFM_READABLE_R8_VALIDATION_PASS=1\n' ...
    'PROTECTION_STRUCTURE_PASS=1\n' ...
    'PRE P=%.4f MW f=%.5f Hz; POST P=%.4f MW f=%.5f Hz\n' ...
    'Vdc=[%.2f %.2f] V, Ibat_peak=%.1f A, AC_limit_pre=%.4f\n'], ...
    a(2)/1e6,a(4),b(2)/1e6,b(4),min(r(event,7)),max(r(event,7)), ...
    max(abs(r(event,8))),mean(r(pre,14)));
close_system(modelName,0);
